// Generated by Mochi compiler v0.10.26 on 2025-07-16T15:41:08Z
fn main() {
    fn boom() -> bool {
        println!("boom");
        return true;
    }
    println!("{}", (1 < 2) && (2 < 3) && (3 < 4));
    println!("{}", (1 < 2) && (2 > 3) && boom());
    println!("{}", (1 < 2) && (2 < 3) && (3 > 4) && boom());
}
