// Generated by Mochi compiler v0.10.26 on 2025-07-16T17:41:55Z
fn main() {
    fn outer(x: i32) -> i32 {
        let inner = move |y: i32| -> i32 {
            return x + y;
        };
        return inner(5);
    }
    println!("{}", outer(3));
}
