// Generated by Mochi compiler v0.10.24 on 2025-07-13T03:59:15Z
#include <stdio.h>
#include <stdlib.h>

typedef struct {
  int inner;
} OuterItem;
typedef struct {
  int len;
  OuterItem *data;
} list_OuterItem;
static list_OuterItem list_OuterItem_create(int len) {
  list_OuterItem l;
  l.len = len;
  l.data = calloc(len, sizeof(OuterItem));
  if (!l.data && len > 0) {
    fprintf(stderr, "alloc failed\n");
    exit(1);
  }
  return l;
}

typedef struct {
  OuterItem outer;
} DataItem;
typedef struct {
  int len;
  DataItem *data;
} list_DataItem;
static list_DataItem list_DataItem_create(int len) {
  list_DataItem l;
  l.len = len;
  l.data = calloc(len, sizeof(DataItem));
  if (!l.data && len > 0) {
    fprintf(stderr, "alloc failed\n");
    exit(1);
  }
  return l;
}

int main() {
  DataItem data = (DataItem){.outer = (OuterItem){.inner = 1}};
  data.outer.inner = 2;
  {
    int first = 1;
    if (!first)
      printf(" ");
    printf("%d", data.outer.inner);
    first = 0;
    printf("\n");
  }
  return 0;
}
