// Generated by Mochi experimental C compiler
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

static int min_list(const int *a, int n) {
    int m = a[0];
    for (int i = 1; i < n; i++) if (a[i] < m) m = a[i];
    return m;
}

static int max_list(const int *a, int n) {
    int m = a[0];
    for (int i = 1; i < n; i++) if (a[i] > m) m = a[i];
    return m;
}

int main() {
    int nums[] = {3, 1, 4};
    printf("%d\n", min_list(nums, 3));
    printf("%d\n", max_list(nums, 3));
    return 0;
}
