// Generated by Mochi compiler v0.10.25 on 2025-07-14T02:49:34Z
#include <stdio.h>
#include <stdlib.h>

int main() {
  {
    int first = 1;
    if (!first)
      printf(" ");
    printf("%d", (-3));
    first = 0;
    printf("\n");
  }
  {
    int first = 1;
    if (!first)
      printf(" ");
    printf("%d", 5 + ((-2)));
    first = 0;
    printf("\n");
  }
  return 0;
}
