// Generated by Mochi experimental C compiler
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

typedef struct { const char* key; int value; } EntrySI;

void print_list(const int* arr, int n) {
    for (int i = 0; i < n; i++) {
        if (i > 0) printf(" ");
        printf("%d", arr[i]);
    }
    printf("\n");
}

int map_get_str_int(const EntrySI* m, int n, const char* key) {
    for (int i = 0; i < n; i++) if (strcmp(m[i].key, key) == 0) return m[i].value;
    return 0;
}

int main() {
EntrySI m[] = {{"a", 1}, {"b", 2}, {"c", 3}};
print_list((int[]){1, 2, 3}, 3);
    return 0;
}
