// Generated by Mochi transpiler
String _substr(String s, num start, num end) {
  var n = s.length;
  int s0 = start.toInt();
  int e0 = end.toInt();
  if (s0 < 0) s0 += n;
  if (e0 < 0) e0 += n;
  if (s0 < 0) s0 = 0;
  if (s0 > n) s0 = n;
  if (e0 < 0) e0 = 0;
  if (e0 > n) e0 = n;
  if (s0 > e0) s0 = e0;
  return s.substring(s0, e0);
}

int gcd(int a, int b) {
  int x = (a < 0 ? -a : a);
  int y = (b < 0 ? -b : b);
  while (y != 0) {
    int t = x % y;
    x = y;
    y = t;
  }
  return x;
}

int find_mod_inverse(int a, int m) {
  if (gcd(a, m) != 1) {
    error("mod inverse of " + (a).toString() + " and " + (m).toString() + " does not exist");
  }
  int u1 = 1;
  int u2 = 0;
  int u3 = a;
  int v1 = 0;
  int v2 = 1;
  int v3 = m;
  while (v3 != 0) {
    int q = u3 ~/ v3;
    int t1 = u1 - q * v1;
    int t2 = u2 - q * v2;
    int t3 = u3 - q * v3;
    u1 = v1;
    u2 = v2;
    u3 = v3;
    v1 = t1;
    v2 = t2;
    v3 = t3;
  }
  int res = u1 % m;
  if (res < 0) {
    res = res + m;
  }
  return res;
}

void main() {
  print((find_mod_inverse(3, 11)).toString());
  print((find_mod_inverse(7, 26)).toString());
  print((find_mod_inverse(11, 26)).toString());
  print((find_mod_inverse(17, 43)).toString());
}
