// Generated by Mochi compiler v0.10.28 on 2025-07-18T03:27:02Z
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    static void Main()
    {
        List<int> data = new List<int> { 1, 2 };
        bool flag = Enumerable.Any(data.Where(x => (x == 1)).Select(x => x).ToList());
        Console.WriteLine(flag);
    }
}
