// Generated by Mochi 0.10.31 on 2025-07-20 00:41:42 GMT+7
#include <stdio.h>
#include <string.h>

int add(int a, int b) {
    return a + b;
}
int main() {
    printf("%d\n", add(2, 3));
    return 0;
}
