// Generated by Mochi 0.10.32 on 2025-07-19 18:32 UTC
#include <stdio.h>
#include <string.h>

int main(void) {
    const char* s = "catch";
    printf("%d\n", strstr(s, "cat") != NULL);
    printf("%d\n", strstr(s, "dog") != NULL);
    return 0;
}
