// Generated by Mochi transpiler v0.10.31 on 2025-07-20 01:30:18 GMT+7
void main() {
  List<int> numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];
  for (var n in numbers) {
  if (((n % 2) == 0)) {
    continue;
  }
  if ((n > 7)) {
    break;
  }
  print("odd number:", n);
}
}
