{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE NoFieldSelectors #-}
-- Generated by Mochi transpiler v0.10.33 on 2025-07-21 16:07 GMT+7
import qualified Data.Map as Map
m = Map.fromList [("a", 1), ("b", 2)]

main :: IO ()
main = do
    mapM_ (\k -> do
        putStrLn (k)
        ) (Map.keys m)
