package ccode

// Helper requirement keys used by the compiler.
const (
	needStr                 = "str"
	needInput               = "input"
	needIndexString         = "index_string"
	needSliceListInt        = "slice_list_int"
	needSliceString         = "slice_string"
	needListListInt         = "list_list_int"
	needConcatListListInt   = "concat_list_list_int"
	needConcatListInt       = "concat_list_int"
	needListString          = "list_string"
	needConcatListString    = "concat_list_string"
	needConcatString        = "concat_string"
	needCount               = "count"
	needAvg                 = "avg"
	needInListInt           = "in_list_int"
	needInListString        = "in_list_string"
	needSliceListFloat      = "slice_list_float"
	needSliceListString     = "slice_list_string"
	needListFloat           = "list_float"
	needConcatListFloat     = "concat_list_float"
	needUnionListFloat      = "union_list_float"
	needExceptListFloat     = "except_list_float"
	needIntersectListFloat  = "intersect_list_float"
	needInListFloat         = "in_list_float"
	needUnionListInt        = "union_list_int"
	needUnionListString     = "union_list_string"
	needExceptListInt       = "except_list_int"
	needExceptListString    = "except_list_string"
	needIntersectListInt    = "intersect_list_int"
	needIntersectListString = "intersect_list_string"
	needNow                 = "now"
	needJSON                = "json"
)
