// Generated by Mochi transpiler v0.10.31 on 2025-07-20 01:14:27 GMT+7
#include <iostream>
#include <string>

int main() {
    std::cout << std::stoi(std::string("1995")) << std::endl;
    return 0;
}
