// Generated by Mochi transpiler v0.10.31 on 2025-07-20 10:28:37 GMT+7
#include <iostream>
#include <string>
#include <vector>

std::string join(const std::string& s) { return s; }
template<typename T>
std::string join(const std::vector<T>& v) {
    std::string o;
    for (size_t i = 0; i < v.size(); ++i) {
        if (i) o += " ";
        o += std::to_string(v[i]);
    }
    return o;
}

int main() {
    for (auto n : std::vector{1, 2, 3}) {
        std::cout << n << std::endl;
    }
    return 0;
}
