// Generated by Mochi transpiler v0.10.31 on 2025-07-20 01:14:25 GMT+7
#include <iostream>
#include <string>
#include <algorithm>
#include <type_traits>

int main() {
    auto s = std::string("catch");
    std::cout << ([&](const auto& c, const auto& v){ if constexpr(std::is_same_v<std::decay_t<decltype(c)>, std::string>) { return c.find(v) != std::string::npos; } else { return std::find(c.begin(), c.end(), v) != c.end(); } } )(s, std::string("cat")) << std::endl;
    std::cout << ([&](const auto& c, const auto& v){ if constexpr(std::is_same_v<std::decay_t<decltype(c)>, std::string>) { return c.find(v) != std::string::npos; } else { return std::find(c.begin(), c.end(), v) != c.end(); } } )(s, std::string("dog")) << std::endl;
    return 0;
}
