// Generated by Mochi compiler v0.10.28 on 2025-07-18T07:06:50Z
const std = @import("std");

const M = struct {
    a: i32,
    b: i32,
};
const m = M{
    .a = 1,
    .b = 2,
}; // M

pub fn main() void {
    std.debug.print("{s}\n", .{"a"});
    std.debug.print("{s}\n", .{"c"});
}
