// Generated by Mochi compiler v0.10.26 on 2025-07-16T17:35:31Z
fun String.starts_with(prefix: String): Boolean = this.startsWith(prefix)
// Code generated from for_list_collection.mochi

fun main() {
    for (n in mutableListOf(1, 2, 3)) {
        println(n)
    }
}
