; Generated by Mochi compiler v0.10.26 on 2025-07-16T16:56:32Z
(ns main)

(defn -main []
  (println (+ 1 (* 2 3)))
  (println (* (+ 1 2) 3))
  (println (+ (* 2 3) 1))
  (println (* 2 (+ 3 1)))
)

(-main)
