//go:build ignore

// Generated by Mochi v0.10.32 on 2025-07-20 21:36:20 GMT+7
package main

import (
	"fmt"
	"strings"
)

func makeAdder(n int) func(int) int {
	return func(x int) int {
		return (x + n)
	}
}

var add10 func(int) int = makeAdder(10)

func main() {
	fmt.Println(strings.TrimSpace(fmt.Sprint(add10(7))))
}
