//go:build ignore

// Generated by Mochi v0.10.31 on 2025-07-20 16:34:36 GMT+7
package main

import (
	"fmt"
)

var data []int = []int{1, 2}

var flag bool = (len(func() []int {
	_res := []int{}
	for _, x := range data {
		if x == 1 {
			_res = append(_res, x)
		}
	}
	return _res
}()) > 0)

func main() {
	fmt.Println(func() int {
		if flag {
			return 1
		}
		return 0
	}())
}
