//go:build ignore

// Generated by Mochi v0.10.31 on 2025-07-20 09:08:15 GMT+7
package main

import (
	"fmt"
)

func main() {
	var x int = 12
	var msg string = func() any {
		if x > 10 {
			return "yes"
		} else {
			return "no"
		}
	}()
	fmt.Println(func(v any) any {
		if v == nil {
			return "nil"
		}
		return v
	}(msg))
}
