//go:build ignore

// Generated by Mochi v0.10.32 on 2025-07-20 21:36:28 GMT+7
package main

import (
	"fmt"
	"strings"
)

var xs []int = []int{1, 2, 3}

func main() {
	fmt.Println(strings.TrimSpace(fmt.Sprint(func() bool {
		for _, v := range xs {
			if v == 2 {
				return true
			}
		}
		return false
	}())))
	fmt.Println(strings.TrimSpace(fmt.Sprint(func() int {
		if !func() bool {
			for _, v := range xs {
				if v == 5 {
					return true
				}
			}
			return false
		}() {
			return 1
		}
		return 0
	}())))
}
