//go:build ignore

// Generated by Mochi v0.10.31 on 2025-07-20 09:08:18 GMT+7
package main

import (
	"fmt"
)

func main() {
	var nums []int = []int{1, 2}
	nums[1] = 3
	fmt.Println(func(v any) any {
		if v == nil {
			return "nil"
		}
		return v
	}(nums[1]))
}
