//go:build ignore

// Generated by Mochi v0.10.33 on 2025-07-21 16:15:54 GMT+7
package main

import (
	"fmt"
)

var x int = 3

var y int = 4

var m map[string]int = map[string]int{"a": x, "b": y}

func main() {
	fmt.Println(m["a"], m["b"])
}
