//go:build ignore

// Generated by Mochi v0.10.31 on 2025-07-20 01:02:20 GMT+7
package main

import (
	"fmt"
)

func triple(x int) int {
	return (x * 3)
}

func main() {
	fmt.Println(func(v any) string {
		s := fmt.Sprint(v)
		if s == "<nil>" {
			return "null"
		}
		return s
	}(triple((1 + 2))))
}
