//go:build ignore

// Generated by Mochi v0.10.32 on 2025-07-21 11:02:21 GMT+7
package main

import (
	"fmt"
)

var nums []int = []int{1, 2, 3}

var result []float64 = func() []float64 {
	res := []float64{}
	for _, n := range nums {
		if n > 1 {
			res = append(res, func() int {
				s := 0
				for _, n := range n {
					s += n
				}
				return s
			}())
		}
	}
	return res
}()

func main() {
	fmt.Println(result)
}
