// Generated by Mochi compiler v0.10.25 on 2025-07-13T05:24:17Z
// cast_string_to_int.mochi
public class CastStringToInt {
    public static void main(String[] args) {
    System.out.println(Integer.parseInt("1995"));
    }
}
