// Generated by Mochi compiler v0.10.26 on 2025-07-16T15:40:27Z
// closure.mochi
import java.util.function.*;

public class Closure {
    static IntUnaryOperator makeAdder(int n) {
        return x -> x + n;
    }
    public static void main(String[] args) {
    IntUnaryOperator add10 = makeAdder(10);
    System.out.println(add10.applyAsInt(7));
    }
}
