package asyncbridge

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"mochi/package3/dotnet/typemap"
)

// MethodSpec is the async bridge's view of one callable method.
// It is used by WrapAsync and EmitAsyncWrapperCS to produce synchronous
// [UnmanagedCallersOnly] wrappers for Task<T>-returning methods.
type MethodSpec struct {
	// Name is the C# method name (e.g. "MyClass_GetUserAge").
	Name string
	// IsAsync indicates the method returns Task<T> or ValueTask<T>.
	IsAsync bool
	// ReturnKind is the Mochi Kind of the inner type (KindUnit for void).
	ReturnKind typemap.Kind
	// ReturnType is a human-readable return type label (e.g. "TaskOfInt64").
	ReturnType string
	// ParamNames is the list of parameter names.
	ParamNames []string
	// ParamCSharpTypes is the list of C# parameter types.
	ParamCSharpTypes []string
}

// WrapAsync takes a MethodSpec with IsAsync=true and returns a MethodSpec for
// the synchronous [UnmanagedCallersOnly] wrapper.
// The wrapper name is the original name with "_Sync" appended.
func WrapAsync(m MethodSpec) MethodSpec {
	return MethodSpec{
		Name:             m.Name + "_Sync",
		IsAsync:          false,
		ReturnKind:       m.ReturnKind,
		ReturnType:       m.ReturnType,
		ParamNames:       m.ParamNames,
		ParamCSharpTypes: m.ParamCSharpTypes,
	}
}

// EmitAsyncWrapperCS writes a C# file containing ManualResetEventSlim wrappers
// for the given async methods. The generated file uses [UnmanagedCallersOnly]
// and is safe to call from native code without deadlocking.
func EmitAsyncWrapperCS(methods []MethodSpec, outPath string) error {
	cs := buildAsyncWrapperCS(methods)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("asyncbridge: mkdir: %w", err)
	}
	return os.WriteFile(outPath, []byte(cs), 0o644)
}

func buildAsyncWrapperCS(methods []MethodSpec) string {
	var b strings.Builder
	b.WriteString("// Generated by mochi/package3/dotnet/asyncbridge; do not edit.\n")
	b.WriteString("using System.Runtime.InteropServices;\n")
	b.WriteString("using System.Threading;\n\n")
	b.WriteString("namespace Mochi.AsyncBridge;\n\n")
	b.WriteString("public static class AsyncWrapper\n{\n")
	for _, m := range methods {
		if !m.IsAsync {
			continue
		}
		b.WriteString(emitAsyncWrapperMethod(m))
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func emitAsyncWrapperMethod(m MethodSpec) string {
	csRetType := kindToCSharp(m.ReturnKind)
	var params strings.Builder
	for i, name := range m.ParamNames {
		if i > 0 {
			params.WriteString(", ")
		}
		csType := "nint"
		if i < len(m.ParamCSharpTypes) {
			csType = m.ParamCSharpTypes[i]
		}
		fmt.Fprintf(&params, "%s %s", csType, name)
	}

	var argList strings.Builder
	for i, name := range m.ParamNames {
		if i > 0 {
			argList.WriteString(", ")
		}
		argList.WriteString(name)
	}

	isVoid := m.ReturnKind == typemap.KindUnit
	var b strings.Builder
	b.WriteString("    [UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]\n")
	fmt.Fprintf(&b, "    public static %s %s(%s)\n    {\n", csRetType, m.Name+"_Sync", params.String())
	b.WriteString("        var __mre = new ManualResetEventSlim(false);\n")
	if !isVoid {
		fmt.Fprintf(&b, "        %s __result = default;\n", csRetType)
	}
	b.WriteString("        Exception? __ex = null;\n")
	b.WriteString("        Task.Run(async () =>\n        {\n")
	b.WriteString("            try\n            {\n")
	if isVoid {
		fmt.Fprintf(&b, "                await %s(%s).ConfigureAwait(false);\n", m.Name, argList.String())
	} else {
		fmt.Fprintf(&b, "                __result = await %s(%s).ConfigureAwait(false);\n", m.Name, argList.String())
	}
	b.WriteString("            }\n            catch (Exception __e) { __ex = __e; }\n")
	b.WriteString("            finally { __mre.Set(); }\n")
	b.WriteString("        });\n")
	b.WriteString("        __mre.Wait();\n")
	b.WriteString("        if (__ex != null) System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(__ex);\n")
	if !isVoid {
		b.WriteString("        return __result;\n")
	}
	b.WriteString("    }\n")
	return b.String()
}

// kindToCSharp maps a typemap.Kind to a C# type name.
func kindToCSharp(k typemap.Kind) string {
	switch k {
	case typemap.KindBool:
		return "bool"
	case typemap.KindInt, typemap.KindInt64:
		return "long"
	case typemap.KindUInt, typemap.KindUInt64:
		return "ulong"
	case typemap.KindFloat, typemap.KindFloat64:
		return "double"
	case typemap.KindString:
		return "nint"
	case typemap.KindUnit:
		return "void"
	default:
		return "nint"
	}
}
