# Code generated by Mochi transpiler.
# Version 0.10.37, generated on 2025-07-23 10:40 +0700
result = ""
for i in range(1, 101):
    j = 1
    while j * j < i:
        j = j + 1
    if j * j == i:
        result = result + "O"
    else:
        result = result + "-"
print(result)
