# Code generated by Mochi transpiler.
# Version 0.10.39, generated on 2025-07-24 18:31 +0700
import sys
sys.set_int_max_str_digits(0)

def fetch_():
    return ""
def example7():
    x = fetch_()
    if x == "cheese":
        None
    else:
        if someCondition():
            None
def someCondition():
    return False
