# Code generated by Mochi transpiler.
# Version 0.10.39, generated on 2025-07-24 20:06 +0700
import sys
sys.set_int_max_str_digits(0)

def listToStringInts(xs):
    s = "["
    i = 0
    while i < len(xs):
        s = s + str(int(xs[i]))
        if i < len(xs) - 1:
            s = s + " "
        i = i + 1
    return s + "]"
def deconv(g, f):
    h = []
    n = 0
    hn = len(g) - len(f) + 1
    while n < hn:
        v = g[n]
        lower = 0
        if n >= len(f):
            lower = n - len(f) + 1
        i = lower
        while i < n:
            v = v - h[i] * f[n - i]
            i = i + 1
        v = v / f[0]
        h = h + [v]
        n = n + 1
    return h
def main():
    h = [-8.0, -9.0, -3.0, -1.0, -6.0, 7.0]
    f = [-3.0, -6.0, -1.0, 8.0, -6.0, 3.0, -1.0, -9.0, -9.0, 3.0, -2.0, 5.0, 2.0, -2.0, -7.0, -1.0]
    g = [24.0, 75.0, 71.0, -34.0, 3.0, 22.0, -45.0, 23.0, 245.0, 25.0, 52.0, 25.0, -67.0, -96.0, 96.0, 31.0, 55.0, 36.0, 29.0, -43.0, -7.0]
    print(listToStringInts(h))
    print(listToStringInts(deconv(g, f)))
    print(listToStringInts(f))
    print(listToStringInts(deconv(g, h)))
main()
