# Code generated by Mochi transpiler.
# Version 0.10.41, generated on 2025-07-27 12:17 +0700
import sys
sys.set_int_max_str_digits(0)

maxNumber = 100000000
dsum = []
dcount = []
i = 0
while i <= maxNumber:
    dsum = dsum + [1]
    dcount = dcount + [1]
    i = i + 1
def pad8(n):
    s = str(n)
    while len(s) < 8:
        s = " " + s
    sys.exit(s)
i = 2
while i <= maxNumber:
    j = i + i
    while j <= maxNumber:
        if dsum[j] == j:
            print(pad8(j) + " equals the sum of its first " + str(dcount[j]) + " divisors")
        dsum[j] = dsum[j] + i
        dcount[j] = dcount[j] + 1
        j = j + i
    i = i + 1
