// Generated by Mochi C# compiler
using System;
using System.Collections.Generic;

public class Program {
	static string intToRoman(long num) {
		long[] values = new [] { 1000L, 900L, 500L, 400L, 100L, 90L, 50L, 40L, 10L, 9L, 5L, 4L, 1L };
		string[] symbols = new [] { "M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I" };
		string result = "";
		long i = 0L;
		while ((num > 0L)) {
			while ((num >= values[i])) {
				result = (result + symbols[i]);
				num = (num - values[i]);
			}
			i = (i + 1L);
		}
		return result;
	}
	
	static void test_example_1() {
		if (!((intToRoman(3L) == "III"))) throw new Exception("expect failed");
	}
	
	static void test_example_2() {
		if (!((intToRoman(58L) == "LVIII"))) throw new Exception("expect failed");
	}
	
	static void test_example_3() {
		if (!((intToRoman(1994L) == "MCMXCIV"))) throw new Exception("expect failed");
	}
	
	static void test_small_numbers() {
		if (!((intToRoman(4L) == "IV"))) throw new Exception("expect failed");
		if (!((intToRoman(9L) == "IX"))) throw new Exception("expect failed");
	}
	
	public static void Main() {
		test_example_1();
		test_example_2();
		test_example_3();
		test_small_numbers();
	}
}
