;; Generated by Mochi 0.10.32 on 2025-07-20 22:17 +0700
#lang typed/racket/no-check
(require racket/list racket/string)

(: numbers (Listof Integer))
(define numbers (list 1 2 3 4 5 6 7 8 9))
(for ([n numbers]) #:break (> n 7) #:unless (= (modulo n 2) 0)
(displayln (format "~a ~a" "odd number:" n))
)
