// Generated by Mochi 0.10.32 on 2025-07-21 10:52 +0700
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

struct NResult {
    public int n;
    public string l;
    public bool b;
    public override string ToString() => JsonSerializer.Serialize(this);
}
class Program {
    static int[] nums = new int[]{1, 2};
    static string[] letters = new string[]{"A", "B"};
    static bool[] bools = new bool[]{true, false};
    static NResult[] combos = (from n in nums from l in letters from b in bools select new NResult{n = n, l = l, b = b}).ToArray();
    static void Main() {
        Console.WriteLine("--- Cross Join of three lists ---");
        foreach (var c in combos) {
    Console.WriteLine(string.Join(" ", new object[]{c.n, c.l, c.b}).TrimEnd());
}
    }
}
