// Generated by Mochi
using System;
using System.Linq;

class Program {
    static void Main() {
        Console.WriteLine((new[]{1, 2}.Concat(new[]{2, 3}).Distinct().ToArray()));
        Console.WriteLine((new[]{1, 2, 3}.Except(new[]{2}).ToArray()));
        Console.WriteLine((new[]{1, 2, 3}.Intersect(new[]{2, 4}).ToArray()));
        Console.WriteLine((new[]{1, 2}.Concat(new[]{2, 3}).ToArray()).Length);
    }
}
