// Generated by Mochi transpiler v0.10.33 on 2025-07-21 18:51:36 GMT+7
import Foundation
let customers = [["id": 1, "name": "Alice"], ["id": 2, "name": "Bob"], ["id": 3, "name": "Charlie"]]
let orders = [["id": 100, "customerId": 1, "total": 250], ["id": 101, "customerId": 2, "total": 125], ["id": 102, "customerId": 1, "total": 300]]
let result = ({ var _res: [[String: Any]] = []
for o in orders {
    for c in customers {
        _res.append(["orderId": (o["id"]! as! Int), "orderCustomerId": (o["customerId"]! as! Int), "pairedCustomerName": c["name"]!, "orderTotal": (o["total"]! as! Int)])
    }
}
return _res })()
print("--- Cross Join: All order-customer pairs ---")
for entry in result {
    print("Order", String(describing: entry["orderId"]!), "(customerId:", String(describing: entry["orderCustomerId"]!), ", total: $", String(describing: entry["orderTotal"]!), ") paired with", String(describing: entry["pairedCustomerName"]!))
}
