// Generated by Mochi transpiler v0.10.33 on 2025-07-21 18:52:39 GMT+7
import Foundation
let customers = [["id": 1, "name": "Alice"], ["id": 2, "name": "Bob"], ["id": 3, "name": "Charlie"]]
let orders = [["id": 100, "customerId": 1, "total": 250], ["id": 101, "customerId": 2, "total": 125], ["id": 102, "customerId": 1, "total": 300], ["id": 103, "customerId": 4, "total": 80]]
let result = ({ var _res: [[String: Any]] = []
for o in orders {
    for c in customers {
        if ((o["customerId"]! as! Int) == (c["id"]! as! Int)) {
            _res.append(["orderId": (o["id"]! as! Int), "customerName": c["name"]!, "total": (o["total"]! as! Int)])
        }
    }
}
return _res })()
print("--- Orders with customer info ---")
for entry in result {
    print("Order", String(describing: entry["orderId"]!), "by", String(describing: entry["customerName"]!), "- $", String(describing: entry["total"]!))
}
