//go:build ignore

// Generated by Mochi v0.10.52 on 2025-08-01 19:07:04 GMT+7
package main

import (
	"fmt"
)

func fibonacciWord(n int) string {
	var a string = "1"
	_ = a
	var b string = "0"
	_ = b
	var i int = 1
	_ = i
	for i < n {
		var tmp string = b
		_ = tmp
		b = (b + a)
		a = tmp
		i = (i + 1)
	}
	return a
}

func mochiMain() {
	var wf string = fibonacciWord(23)
	_ = wf
	fmt.Println(fmt.Sprint(len(wf)))
}

func main() {
	mochiMain()
}
