# Code generated by Mochi transpiler.
# Version 0.10.34, generated on 2025-07-22 09:56 +0700
import mochi.runtime.ffi.go.testpkg as testpkg

print(testpkg.Add(2, 3))
print(testpkg.Pi)
print(testpkg.Answer)
