# Generated by Mochi transpiler v0.10.33 on 2025-07-21 16:07 +0700
customers = [{"id": 1, "name": "Alice"}, {"id": 2, "name": "Bob"}, {"id": 3, "name": "Charlie"}, {"id": 4, "name": "Diana"}]
orders = [{"id": 100, "customerId": 1, "total": 250}, {"id": 101, "customerId": 2, "total": 125}, {"id": 102, "customerId": 1, "total": 300}, {"id": 103, "customerId": 5, "total": 80}]
result = [{"order": o, "customer": c} for o in orders for c in customers if o["customerId"] == c["id"]] + [(lambda c: {"order": o, "customer": c})(None) for o in orders if not any([o["customerId"] == c["id"] for c in customers])] + [(lambda o: {"order": o, "customer": c})(None) for c in customers if not any([o["customerId"] == c["id"] for o in orders])]
print("--- Outer Join using syntax ---")
for row in result:
    if row["order"]:
        if row["customer"]:
            print(" ".join(str(x) for x in ["Order", row["order"]["id"], "by", row["customer"]["name"], "- $", row["order"]["total"]]).rstrip())
        else:
            print(" ".join(str(x) for x in ["Order", row["order"]["id"], "by", "Unknown", "- $", row["order"]["total"]]).rstrip())
    else:
        print(" ".join(str(x) for x in ["Customer", row["customer"]["name"], "has no orders"]).rstrip())
