//go:build ignore

// Generated by Mochi compiler v0.10.26 on 1970-01-01T00:00:00Z

package main

import (
	"fmt"
)

type v map[string]any

func main() {
	for _, n := range []int{1, 2, 3} {
		fmt.Println(n)
	}
}
