//go:build ignore

// Generated by Mochi compiler v0.10.26 on 2025-07-16T16:36:49Z

package main

import (
	"fmt"
)

type v map[string]any

func main() {
	x := 5
	if x > 3 {
		fmt.Println("big")
	} else {
		fmt.Println("small")
	}
}
