//go:build ignore

// Generated by Mochi compiler v0.10.26 on 1970-01-01T00:00:00Z

package main

import (
	"fmt"
)

type Book struct {
	Title  string `json:"title"`
	Author Person `json:"author"`
}

type Person struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type v map[string]any

func main() {
	book := Book{Title: "Go", Author: Person{Name: "Bob", Age: 42}}
	_ = book
	fmt.Println(book.Author.Name)
}
