(define data (list 1 2))
(define flag (exists (let ((_res '()))
  (for-each (lambda (x)
    (when (equal? x 1)
      (set! _res (append _res (list x)))
    )
  ) (if (string? data) (string->list data) data))
  _res)))
(begin (display flag) (newline))
