(define (outer x)
  (call/cc (lambda (return)
    (define (inner y)
      (call/cc (lambda (return)
        (return (+ x y))
      ))
    )
    (return (inner 5))
  ))
)

(begin (display (outer 3)) (newline))
