(define (map-get m k)
    (let ((p (assoc k m)))
        (if p (cdr p) '()))
)
(define (map-set m k v)
    (let ((p (assoc k m)))
        (if p
            (begin (set-cdr! p v) m)
            (cons (cons k v) m)))
)
(import (chibi string))

(define s "catch")
(begin (display (if (string-contains s "cat") #t #f)) (newline))
(begin (display (if (string-contains s "dog") #t #f)) (newline))
