// Generated by Mochi Zig transpiler on 2025-07-20 03:39 +0000
const std = @import("std");

pub fn main() void {
    const x = 12;
    const msg = if (x > 10) "yes" else "no";
    std.debug.print("{any}\n", .{msg});
}
