#!/usr/bin/env escript
-module(main).
-export([main/1]).

% Generated by Mochi transpiler v0.10.31 (5d6f4afbd) on 2025-07-20 10:18 +0700

main(_) ->
    X = 8,
    Msg = (case (X > 10) of
    true -> "big";
    _ -> (case (X > 5) of
    true -> "medium";
    _ -> "small"
end)
end),
    io:format("~s~n", [Msg]).
