#!/usr/bin/env escript
-module(main).
-export([main/1]).

% Generated by Mochi transpiler v0.10.32 (04e9954db) on 2025-07-20 22:28 +0700

main(_) ->
    Book = #{title => "Go", author => #{name => "Bob", age => 42}},
    io:format("~p~n", [maps:get(name, maps:get(author, Book))]).
