package cgen

import (
	"bytes"
	"errors"
	"fmt"

	"mochi/compiler3/ir"
	"mochi/compiler3/verify"
)

// ErrUnsupportedOp is returned when the IR carries an op the Phase
// 4.0 emitter does not yet lower. The driver maps this to a clean
// "AOT target unsupported, falling back to interpreter" failure
// rather than emitting a .c file that the system cc would reject or
// (worse) silently mis-link.
var ErrUnsupportedOp = errors.New("cgen: unsupported IR op for Phase 4.0")

// ErrUnsupportedType is returned when an SSA value carries a type
// outside the Phase 4.0 scalar set (i64, f64, bool, unit). Same
// rationale as ErrUnsupportedOp.
var ErrUnsupportedType = errors.New("cgen: unsupported IR type for Phase 4.0")

// Program is the multi-function unit the emitter consumes. Main, if
// non-empty, names a no-parameter function to invoke from the
// generated `int main(void)`. The Main function's result type
// controls how main reports it to the host process: TypeI64 prints
// `%lld\n` to stdout (so the Phase 4.0 gate can byte-compare against
// `mochi run`), TypeBool prints `0` or `1`, TypeF64 prints `%.17g`,
// TypeUnit prints nothing. Other types fall under ErrUnsupportedType.
type Program struct {
	Funcs []*ir.Function
	Main  string
}

// Emit lowers p to a C99 source file. The output is self-contained:
// it includes <stdint.h>, <stdio.h>, and <math.h>; it never imports
// any Mochi runtime header (Phase 4.0 ships scalar-only IR which
// needs none). Callers feed the returned bytes to the system cc via
// the build/c driver.
func Emit(p *Program) ([]byte, error) {
	for _, fn := range p.Funcs {
		if err := verify.Function(fn); err != nil {
			return nil, fmt.Errorf("verify %s: %w", fn.Name, err)
		}
	}
	var buf bytes.Buffer
	buf.WriteString("/* Code generated by compiler3/emit/c. DO NOT EDIT. */\n")
	buf.WriteString("#include <stdint.h>\n")
	buf.WriteString("#include <stdio.h>\n")
	buf.WriteString("#include <math.h>\n\n")

	for _, fn := range p.Funcs {
		emitPrototype(&buf, fn)
	}
	if len(p.Funcs) > 0 {
		buf.WriteString("\n")
	}
	for _, fn := range p.Funcs {
		if err := emitFunc(&buf, fn); err != nil {
			return nil, fmt.Errorf("emit %s: %w", fn.Name, err)
		}
	}
	if p.Main != "" {
		if err := emitMain(&buf, p); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

func emitPrototype(w *bytes.Buffer, fn *ir.Function) {
	fmt.Fprintf(w, "static %s %s(", cType(fn.Result), fn.Name)
	if len(fn.Params) == 0 {
		w.WriteString("void")
	} else {
		for i, pid := range fn.Params {
			if i > 0 {
				w.WriteString(", ")
			}
			fmt.Fprintf(w, "%s %s", cType(fn.Values[pid].Type), valueName(pid))
		}
	}
	w.WriteString(");\n")
}

func emitFunc(w *bytes.Buffer, fn *ir.Function) error {
	fmt.Fprintf(w, "static %s %s(", cType(fn.Result), fn.Name)
	if len(fn.Params) == 0 {
		w.WriteString("void")
	} else {
		for i, pid := range fn.Params {
			if i > 0 {
				w.WriteString(", ")
			}
			fmt.Fprintf(w, "%s %s", cType(fn.Values[pid].Type), valueName(pid))
		}
	}
	w.WriteString(") {\n")

	// Declare every non-param, non-fnref value at the function head
	// with a zero initializer. C99 allows goto across declarations
	// only when no VLA is jumped over; Phase 4.0's scalar-only set
	// has no VLAs, so label-driven control flow is unconstrained.
	for _, v := range fn.Values {
		if v.Op == ir.OpParam || v.Op == ir.OpFnRef {
			continue
		}
		ct := cType(v.Type)
		if ct == "" || ct == "void" {
			continue
		}
		fmt.Fprintf(w, "    %s %s = 0;\n", ct, valueName(v.ID))
	}

	rpo := reversePostorder(fn)
	for i, bid := range rpo {
		blk := fn.Block(bid)
		if i > 0 {
			fmt.Fprintf(w, "L%d:;\n", bid)
		}
		for _, vid := range blk.Values {
			v := fn.Values[vid]
			if v.Op == ir.OpPhi {
				continue
			}
			if err := emitValue(w, fn, v); err != nil {
				return err
			}
		}
		if err := emitTerminator(w, fn, blk); err != nil {
			return err
		}
	}
	w.WriteString("}\n\n")
	return nil
}

func emitValue(w *bytes.Buffer, fn *ir.Function, v ir.Value) error {
	name := valueName(v.ID)
	switch v.Op {
	case ir.OpParam:
		return nil
	case ir.OpConst:
		switch v.Type {
		case ir.TypeI64:
			// LLONG_MIN cannot be written as a positive literal in C
			// without a suffix; the safe form is (a - 1) where a is
			// (-LLONG_MAX). The cast to int64_t silences width warnings.
			if v.Const == -1<<63 {
				fmt.Fprintf(w, "    %s = (int64_t)(-9223372036854775807LL - 1);\n", name)
			} else {
				fmt.Fprintf(w, "    %s = (int64_t)%dLL;\n", name, v.Const)
			}
		case ir.TypeF64:
			// Bit-cast through a uint64 union: the IR carries f64
			// consts as raw bit patterns in v.Const.
			fmt.Fprintf(w, "    { union { uint64_t u; double d; } _c%d; _c%d.u = (uint64_t)%dULL; %s = _c%d.d; }\n",
				v.ID, v.ID, uint64(v.Const), name, v.ID)
		case ir.TypeBool:
			val := 0
			if v.Const != 0 {
				val = 1
			}
			fmt.Fprintf(w, "    %s = %d;\n", name, val)
		default:
			return fmt.Errorf("%w: OpConst type %s", ErrUnsupportedType, v.Type)
		}
	case ir.OpAddI64, ir.OpSubI64, ir.OpMulI64, ir.OpDivI64, ir.OpModI64:
		op := i64BinaryOp(v.Op)
		fmt.Fprintf(w, "    %s = %s %s %s;\n", name, valueName(v.Args[0]), op, valueName(v.Args[1]))
	case ir.OpNegI64:
		fmt.Fprintf(w, "    %s = -%s;\n", name, valueName(v.Args[0]))
	case ir.OpAddI64Imm, ir.OpSubI64Imm, ir.OpMulI64Imm, ir.OpDivI64Imm, ir.OpModI64Imm:
		op := i64ImmBinaryOp(v.Op)
		fmt.Fprintf(w, "    %s = %s %s (int64_t)%dLL;\n", name, valueName(v.Args[0]), op, v.Const)
	case ir.OpAddF64, ir.OpSubF64, ir.OpMulF64, ir.OpDivF64:
		op := f64BinaryOp(v.Op)
		fmt.Fprintf(w, "    %s = %s %s %s;\n", name, valueName(v.Args[0]), op, valueName(v.Args[1]))
	case ir.OpNegF64:
		fmt.Fprintf(w, "    %s = -%s;\n", name, valueName(v.Args[0]))
	case ir.OpCmpEqI64, ir.OpCmpNeI64, ir.OpCmpLtI64, ir.OpCmpLeI64, ir.OpCmpGtI64, ir.OpCmpGeI64:
		op := i64CmpOp(v.Op)
		fmt.Fprintf(w, "    %s = (%s %s %s) ? 1 : 0;\n", name, valueName(v.Args[0]), op, valueName(v.Args[1]))
	case ir.OpCmpEqI64Imm, ir.OpCmpNeI64Imm, ir.OpCmpLtI64Imm, ir.OpCmpLeI64Imm, ir.OpCmpGtI64Imm, ir.OpCmpGeI64Imm:
		op := i64ImmCmpOp(v.Op)
		fmt.Fprintf(w, "    %s = (%s %s (int64_t)%dLL) ? 1 : 0;\n", name, valueName(v.Args[0]), op, v.Const)
	case ir.OpCall, ir.OpTailCall:
		// Phase 4.0 admits intra-program calls so a Main can invoke a
		// helper. Cross-module FFI (OpCallGo) is out of scope for 4.0.
		if int(v.Const) >= len(fn.Values) && int(v.Const) < 0 {
			return fmt.Errorf("%w: OpCall Const out of range", ErrUnsupportedOp)
		}
		// The callee is named by v.Const indexing into the caller's
		// owning Program; the emitter resolves it via the closure
		// passed to emitValueInProgram. Phase 4.0 keeps the indirection
		// simple: see emitFuncInProgram.
		return fmt.Errorf("%w: OpCall needs Program context", ErrUnsupportedOp)
	case ir.OpPhi:
		return nil
	case ir.OpFnRef:
		return nil
	default:
		return fmt.Errorf("%w: %s", ErrUnsupportedOp, v.Op)
	}
	return nil
}

func emitTerminator(w *bytes.Buffer, fn *ir.Function, blk *ir.Block) error {
	emitPhiAssignments := func(succID uint32) {
		succ := fn.Block(succID)
		for _, vid := range succ.Values {
			v := fn.Values[vid]
			if v.Op != ir.OpPhi {
				continue
			}
			for i := 0; i < len(v.Args); i += 2 {
				if v.Args[i] == blk.ID {
					fmt.Fprintf(w, "    %s = %s;\n", valueName(v.ID), valueName(v.Args[i+1]))
				}
			}
		}
	}
	switch blk.Term.Kind {
	case ir.TermJump:
		emitPhiAssignments(blk.Term.Target)
		fmt.Fprintf(w, "    goto L%d;\n", blk.Term.Target)
	case ir.TermBranch:
		fmt.Fprintf(w, "    if (%s) {\n", valueName(blk.Term.Value))
		emitPhiAssignments(blk.Term.IfTrue)
		fmt.Fprintf(w, "        goto L%d;\n    }\n", blk.Term.IfTrue)
		emitPhiAssignments(blk.Term.IfFalse)
		fmt.Fprintf(w, "    goto L%d;\n", blk.Term.IfFalse)
	case ir.TermReturn:
		if fn.Result == ir.TypeUnit || fn.Result == ir.TypeInvalid {
			w.WriteString("    return;\n")
		} else {
			fmt.Fprintf(w, "    return %s;\n", valueName(blk.Term.Value))
		}
	default:
		return fmt.Errorf("%w: terminator %d", ErrUnsupportedOp, blk.Term.Kind)
	}
	return nil
}

func emitMain(w *bytes.Buffer, p *Program) error {
	var fn *ir.Function
	for _, f := range p.Funcs {
		if f.Name == p.Main {
			fn = f
			break
		}
	}
	if fn == nil {
		return fmt.Errorf("cgen: Main %q not found in Funcs", p.Main)
	}
	if len(fn.Params) != 0 {
		return fmt.Errorf("cgen: Main %q must take zero parameters", p.Main)
	}
	w.WriteString("int main(void) {\n")
	switch fn.Result {
	case ir.TypeI64:
		fmt.Fprintf(w, "    int64_t _r = %s();\n", p.Main)
		w.WriteString("    printf(\"%lld\\n\", (long long)_r);\n")
	case ir.TypeF64:
		fmt.Fprintf(w, "    double _r = %s();\n", p.Main)
		w.WriteString("    printf(\"%.17g\\n\", _r);\n")
	case ir.TypeBool:
		fmt.Fprintf(w, "    int _r = %s();\n", p.Main)
		w.WriteString("    printf(\"%d\\n\", _r ? 1 : 0);\n")
	case ir.TypeUnit, ir.TypeInvalid:
		fmt.Fprintf(w, "    %s();\n", p.Main)
	default:
		return fmt.Errorf("%w: Main result type %s", ErrUnsupportedType, fn.Result)
	}
	w.WriteString("    return 0;\n}\n")
	return nil
}

// cType maps an IR Type to the C99 spelling Phase 4.0 supports.
// Returns the empty string for TypeInvalid and "void" for TypeUnit;
// every other type outside the Phase 4.0 scalar set returns "" so
// the caller can detect it via the goTypeForValue analog (empty ->
// skip declaration, since the value cannot appear in well-typed
// Phase 4.0 output).
func cType(t ir.Type) string {
	switch t {
	case ir.TypeI64:
		return "int64_t"
	case ir.TypeF64:
		return "double"
	case ir.TypeBool:
		return "int"
	case ir.TypeUnit, ir.TypeInvalid:
		return "void"
	}
	return ""
}

func valueName(id uint32) string { return fmt.Sprintf("v%d", id) }

func i64BinaryOp(op ir.OpCode) string {
	switch op {
	case ir.OpAddI64:
		return "+"
	case ir.OpSubI64:
		return "-"
	case ir.OpMulI64:
		return "*"
	case ir.OpDivI64:
		return "/"
	case ir.OpModI64:
		return "%"
	}
	return "?"
}

func i64ImmBinaryOp(op ir.OpCode) string {
	switch op {
	case ir.OpAddI64Imm:
		return "+"
	case ir.OpSubI64Imm:
		return "-"
	case ir.OpMulI64Imm:
		return "*"
	case ir.OpDivI64Imm:
		return "/"
	case ir.OpModI64Imm:
		return "%"
	}
	return "?"
}

func f64BinaryOp(op ir.OpCode) string {
	switch op {
	case ir.OpAddF64:
		return "+"
	case ir.OpSubF64:
		return "-"
	case ir.OpMulF64:
		return "*"
	case ir.OpDivF64:
		return "/"
	}
	return "?"
}

func i64CmpOp(op ir.OpCode) string {
	switch op {
	case ir.OpCmpEqI64:
		return "=="
	case ir.OpCmpNeI64:
		return "!="
	case ir.OpCmpLtI64:
		return "<"
	case ir.OpCmpLeI64:
		return "<="
	case ir.OpCmpGtI64:
		return ">"
	case ir.OpCmpGeI64:
		return ">="
	}
	return "?"
}

func i64ImmCmpOp(op ir.OpCode) string {
	switch op {
	case ir.OpCmpEqI64Imm:
		return "=="
	case ir.OpCmpNeI64Imm:
		return "!="
	case ir.OpCmpLtI64Imm:
		return "<"
	case ir.OpCmpLeI64Imm:
		return "<="
	case ir.OpCmpGtI64Imm:
		return ">"
	case ir.OpCmpGeI64Imm:
		return ">="
	}
	return "?"
}

// reversePostorder is the same DFS-RPO the Go emitter uses. We
// duplicate the helper to avoid an import cycle with compiler3/emit/go.
func reversePostorder(fn *ir.Function) []uint32 {
	if len(fn.Blocks) == 0 {
		return nil
	}
	visited := make([]bool, len(fn.Blocks))
	order := make([]uint32, 0, len(fn.Blocks))
	var dfs func(id uint32)
	dfs = func(id uint32) {
		if visited[id] {
			return
		}
		visited[id] = true
		for _, s := range fn.Block(id).Succs {
			dfs(s)
		}
		order = append(order, id)
	}
	dfs(0)
	// Reverse in place.
	for i, j := 0, len(order)-1; i < j; i, j = i+1, j-1 {
		order[i], order[j] = order[j], order[i]
	}
	return order
}
