# Code generated by Mochi transpiler.
# Version 0.10.61, generated on 2025-08-08 17:42 +0700
import json

import sys
sys.set_int_max_str_digits(0)
import os
if os.path.dirname(__file__) in sys.path:
    sys.path.remove(os.path.dirname(__file__))


def panic(msg):
    raise RuntimeError(msg)


def _append(lst, v):
    return (lst or []) + [v]

def exp(x):
    term = 1.0
    sum = 1.0
    n = 1
    while n < 20:
        term = term * x / float(n)
        sum = sum + term
        n = n + 1
    return sum
def soboleva_modified_hyperbolic_tangent(vector, a_value, b_value, c_value, d_value):
    result = []
    i = 0
    while i < len(vector):
        x = vector[i]
        numerator = exp(a_value * x) - exp(-b_value * x)
        denominator = exp(c_value * x) + exp(-d_value * x)
        result = _append(result, numerator / denominator)
        i = i + 1
    return result
def main():
    vector = [5.4, -2.4, 6.3, -5.23, 3.27, 0.56]
    res = soboleva_modified_hyperbolic_tangent(vector, 0.2, 0.4, 0.6, 0.8)
    print(json.dumps(res, indent=2))
main()
