// Generated by Mochi compiler v0.10.24 on 2025-07-13T02:30:22Z
#include <iostream>
#include <string>
#include <unordered_map>

int main() {
  auto m = std::unordered_map<int, std::string>{{1, std::string("a")},
                                                {2, std::string("b")}};
  std::cout << m[1] << std::endl;
  return 0;
}
