// Generated by Mochi transpiler
import 'dart:convert';
import 'dart:io';

int _nowSeed = 0;
bool _nowSeeded = false;
void _initNow() {
  var s = Platform.environment['MOCHI_NOW_SEED'];
  if (s != null && s.isNotEmpty) {
    var v = int.tryParse(s);
    if (v != null) {
      _nowSeed = v;
      _nowSeeded = true;
    }
  }
}
int _now() {
  if (_nowSeeded) {
    _nowSeed = (_nowSeed * 1664525 + 1013904223) % 2147483647;
    return _nowSeed;
  }
  return DateTime.now().microsecondsSinceEpoch;
}

dynamic _substr(dynamic s, num start, num end) {
  int n = s.length;
  int s0 = start.toInt();
  int e0 = end.toInt();
  if (s0 < 0) s0 += n;
  if (e0 < 0) e0 += n;
  if (s0 < 0) s0 = 0;
  if (s0 > n) s0 = n;
  if (e0 < 0) e0 = 0;
  if (e0 > n) e0 = n;
  if (s0 > e0) s0 = e0;
  if (s is String) {
    return s.substring(s0, e0);
  }
  return s.sublist(s0, e0);
}

String _str(dynamic v) => v.toString();

class EuclidResult {
  int x;
  int y;
  EuclidResult({required this.x, required this.y});
}

EuclidResult extended_euclid(int a, int b) {
  if (b == 0) {
    return EuclidResult(x: 1, y: 0);
  }
  EuclidResult res = extended_euclid(b, a % b);
  int k = a ~/ b;
  return EuclidResult(x: res.y, y: res.x - k * res.y);
}

int chinese_remainder_theorem(int n1, int r1, int n2, int r2) {
  EuclidResult res = extended_euclid(n1, n2);
  int x = res.x;
  int y = res.y;
  int m = n1 * n2;
  int n = r2 * x * n1 + r1 * y * n2;
  return (n % m + m) % m;
}

int invert_modulo(int a, int n) {
  EuclidResult res = extended_euclid(a, n);
  int b = res.x;
  if (b < 0) {
    b = (b % n + n) % n;
  }
  return b;
}

int chinese_remainder_theorem2(int n1, int r1, int n2, int r2) {
  int x = invert_modulo(n1, n2);
  int y = invert_modulo(n2, n1);
  int m = n1 * n2;
  int n = r2 * x * n1 + r1 * y * n2;
  return (n % m + m) % m;
}

EuclidResult e1 = extended_euclid(10, 6);
EuclidResult e2 = extended_euclid(7, 5);
void main() {
  var _benchMem0 = ProcessInfo.currentRss;
  var _benchSw = Stopwatch()..start();
  _initNow();
  {
  var _benchMem0 = ProcessInfo.currentRss;
  var _benchSw = Stopwatch()..start();
  print(_str(e1.x) + "," + _str(e1.y));
  print(_str(e2.x) + "," + _str(e2.y));
  print(_str(chinese_remainder_theorem(5, 1, 7, 3)));
  print(_str(chinese_remainder_theorem(6, 1, 4, 3)));
  print(_str(invert_modulo(2, 5)));
  print(_str(invert_modulo(8, 7)));
  print(_str(chinese_remainder_theorem2(5, 1, 7, 3)));
  print(_str(chinese_remainder_theorem2(6, 1, 4, 3)));
  _benchSw.stop();
  var _benchMem1 = ProcessInfo.currentRss;
  print(jsonEncode({"duration_us": _benchSw.elapsedMicroseconds, "memory_bytes": (_benchMem1 - _benchMem0).abs(), "name": "main"}));
}
  _benchSw.stop();
  var _benchMem1 = ProcessInfo.currentRss;
  print(jsonEncode({"duration_us": _benchSw.elapsedMicroseconds, "memory_bytes": (_benchMem1 - _benchMem0).abs(), "name": "main"}));
}
