# Generated by Mochi transpiler v0.10.59 on 2025-08-06 20:30 +0700
require 'json'

$now_seed = 0
$now_seeded = false
s = ENV['MOCHI_NOW_SEED']
if (!s || s == '') && ENV['MOCHI_BENCHMARK']
  s = '1'
end
if s && s != ''
  begin
    $now_seed = Integer(s)
    $now_seeded = true
  rescue StandardError
  end
end
def _now()
  if $now_seeded
    $now_seed += 1_000_000
    $now_seed
  else
    Process.clock_gettime(Process::CLOCK_MONOTONIC, :nanosecond)
  end
end


require 'objspace'
def _mem()
  ObjectSpace.memsize_of_all
end


def _add(a, b)
  if a.is_a?(Array) && b.is_a?(String)
    a.join + b
  elsif a.is_a?(String) && b.is_a?(Array)
    a + b.join
  else
    a + b
  end
end


def _padStart(s, len, ch)
  s.to_s.rjust(len, ch)
end


class String
  alias each each_char
end

start_mem = _mem()
start = _now()
  def pow2(exp)
    result = 1
    i = 0
    while i < exp
      result = result * 2
      i = _add(i, 1)
    end
    return result
  end
  def is_bit_set(number, position)
    shifted = number / pow2(position)
    remainder = shifted % 2
    return remainder == 1
  end
  def set_bit(number, position)
    if is_bit_set(number, position)
      return number
    end
    return _add(number, pow2(position))
  end
  def clear_bit(number, position)
    if is_bit_set(number, position)
      return number - pow2(position)
    end
    return number
  end
  def flip_bit(number, position)
    if is_bit_set(number, position)
      return number - pow2(position)
    end
    return _add(number, pow2(position))
  end
  def get_bit(number, position)
    if is_bit_set(number, position)
      return 1
    end
    return 0
  end
  puts((set_bit(13, 1)).to_s)
  puts((clear_bit(18, 1)).to_s)
  puts((flip_bit(5, 1)).to_s)
  puts((is_bit_set(10, 3)).to_s)
  puts((get_bit(10, 1)).to_s)
end_time = _now()
end_mem = _mem()
result = {"duration_us" => ((end_time - start) / 1000), "memory_bytes" => (end_mem - start_mem), "name" => "main"}
puts(JSON.pretty_generate(result))
