# Code generated by Mochi transpiler.
# Version 0.10.59, generated on 2025-08-07 08:38 +0700
import sys
sys.set_int_max_str_digits(0)
import os
if os.path.dirname(__file__) in sys.path:
    sys.path.remove(os.path.dirname(__file__))

def fizz_buzz(number, iterations):
    if number < 1:
        panic("starting number must be an integer and be more than 0")
    if iterations < 1:
        panic("Iterations must be done more than 0 times to play FizzBuzz")
    out = ""
    n = number
    while n <= iterations:
        if n % 3 == 0:
            out = out + "Fizz"
        if n % 5 == 0:
            out = out + "Buzz"
        if n % 3 != 0 and n % 5 != 0:
            out = out + str(n)
        out = out + " "
        n = n + 1
    return out
print(fizz_buzz(1, 7))
print(fizz_buzz(1, 15))
