# Code generated by Mochi transpiler.
# Version 0.10.59, generated on 2025-08-07 08:38 +0700
import sys
sys.set_int_max_str_digits(0)
import os
if os.path.dirname(__file__) in sys.path:
    sys.path.remove(os.path.dirname(__file__))


def _append(lst, v):
    return (lst or []) + [v]


def _set_index(lst, idx, val):
    if lst is None:
        lst = []
    if idx >= len(lst):
        lst.extend([None] * (idx - len(lst) + 1))
    lst[idx] = val
    return lst

def dp_count(s, n):
    if n < 0:
        return 0
    table = []
    i = 0
    while i <= n:
        table = _append(table, 0)
        i = i + 1
    table[0] = 1
    idx = 0
    while idx < len(s):
        coin_val = s[idx]
        j = coin_val
        while j <= n:
            table[j] = table[j] + table[j - coin_val]
            j = j + 1
        idx = idx + 1
    return table[n]
print(dp_count([1, 2, 3], 4))
print(dp_count([1, 2, 3], 7))
print(dp_count([2, 5, 3, 6], 10))
print(dp_count([10], 99))
print(dp_count([4, 5, 6], 0))
print(dp_count([1, 2, 3], -5))
