;; Generated by Mochi v0.10.32 on 2025-07-21 13:02:02 GMT+7
(ns main)

(require 'clojure.set)

(defrecord Anon1 [a b])

(def data [{:a 1 :b 2} {:a 1 :b 1} {:a 0 :b 5}])

(def sorted (for [x (sort-by (fn [x] [(:a x) (:b x)]) data)] x))

(defn -main []
  (println sorted))

(-main)
