# Generated by Mochi compiler v0.10.26 on 2025-07-16T17:14:00Z
defmodule Main do
  def main do
    # square :: (integer() -> integer())
    square = fn x -> x * x end
    IO.inspect(square.(6))
  end
end

Main.main()
