# Generated by Mochi compiler v0.10.27 on 2025-07-17T08:18:40Z
defmodule Main do
  @m %{"a" => 1, "b" => 2, "c" => 3}
  def main do
    IO.puts(Enum.map_join(Map.values(@m), " ", &inspect(&1)))
  end
end

Main.main()
