>>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. MAIN.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 A PIC 9(2) VALUE 10.
01 B PIC 9(2) VALUE 20.
01 TMP PIC S9(9) VALUE 0.

PROCEDURE DIVISION.
    COMPUTE TMP = A + B
    DISPLAY TMP
    STOP RUN.
