# Generated by Mochi transpiler v0.10.31 on 2025-07-19 13:29:39 GMT+7
x = 8
msg = (x > 10 ? "big" : (x > 5 ? "medium" : "small"))
puts(((msg).is_a?(Array) ? (msg).join(' ') : ((msg) == true ? 1 : ((msg) == false ? 0 : (msg)))))
