# Generated by Mochi transpiler v0.10.37 on 2025-07-23 13:02 +0700

def _input()
  line = STDIN.gets
  line ? line.chomp : ''
end

SomeStruct = Struct.new(:runtimeFields, keyword_init: true)
def main()
  ss = SomeStruct.new(runtimeFields: {})
  puts("Create two fields at runtime: \n")
  i = 1
  while i <= 2
    puts("  Field #" + (i).to_s + ":\n")
    puts("       Enter name  : ")
    name = _input()
    puts("       Enter value : ")
    value = _input()
    fields = ss.runtimeFields
    fields[name] = value
    ss["runtimeFields"] = fields
    puts("\n")
    i = i + 1
  end
  while true
    puts("Which field do you want to inspect ? ")
    name = _input()
    if ss.runtimeFields.key?(name)
      value = ss.runtimeFields[name]
      puts("Its value is '" + value + "'")
      return
    else
      puts("There is no field of that name, try again\n")
    end
  end
end
main()
