# Generated by Mochi transpiler v0.10.39 on 2025-07-24 20:52 +0700

def _add(a, b)
  if a.is_a?(Array) && b.is_a?(String)
    a.join + b
  elsif a.is_a?(String) && b.is_a?(Array)
    a + b.join
  else
    a + b
  end
end


def _padStart(s, len, ch)
  s.rjust(len, ch)
end

def ord(ch)
  if ch == "a"
    return 97
  end
  if ch == "π"
    return 960
  end
  if ch == "A"
    return 65
  end
  return 0
end
def chr(n)
  if n == 97
    return "a"
  end
  if n == 960
    return "π"
  end
  if n == 65
    return "A"
  end
  return "?"
end
puts((ord("A")).to_s)
puts(chr(65))
