// Generated by Mochi C# compiler
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

public class Program {
	static double findMedianSortedArrays(int[] nums1, int[] nums2) {
		var merged = new int[] { };
		var i = 0;
		var j = 0;
		while (((i < nums1.Length) || (j < nums2.Length))) {
			if ((j >= nums2.Length)) {
				merged = merged.Concat(new [] { nums1[i] }).ToArray();
				i = (i + 1);
			} else if ((i >= nums1.Length)) {
				merged = merged.Concat(new [] { nums2[j] }).ToArray();
				j = (j + 1);
			} else if ((nums1[i] <= nums2[j])) {
				merged = merged.Concat(new [] { nums1[i] }).ToArray();
				i = (i + 1);
			} else {
				merged = merged.Concat(new [] { nums2[j] }).ToArray();
				j = (j + 1);
			}
		}
		var total = merged.Length;
		if (((total % 2) == 1)) {
			return _cast<double>(merged[(total / 2)]);
		}
		var mid1 = merged[((total / 2) - 1)];
		var mid2 = merged[(total / 2)];
		return (_cast<double>(((mid1 + mid2))) / 2.000000);
	}
	
	static void test_example_1() {
		if (!((findMedianSortedArrays(new [] { 1, 3 }, new [] { 2 }) == 2.000000))) throw new Exception("expect failed");
	}
	
	static void test_example_2() {
		if (!((findMedianSortedArrays(new [] { 1, 2 }, new [] { 3, 4 }) == 2.500000))) throw new Exception("expect failed");
	}
	
	static void test_empty_first() {
		if (!((findMedianSortedArrays(_cast<int[]>(new dynamic[] { }), new [] { 1 }) == 1.000000))) throw new Exception("expect failed");
	}
	
	static void test_empty_second() {
		if (!((findMedianSortedArrays(new [] { 2 }, _cast<int[]>(new dynamic[] { })) == 2.000000))) throw new Exception("expect failed");
	}
	
	public static void Main() {
		test_example_1();
		test_example_2();
		test_empty_first();
		test_empty_second();
	}
	static T _cast<T>(dynamic v) {
		if (v is T tv) return tv;
		if (typeof(T) == typeof(int)) {
			if (v is int) return (T)v;
			if (v is double) return (T)(object)(int)(double)v;
			if (v is float) return (T)(object)(int)(float)v;
		}
		if (typeof(T) == typeof(double)) {
			if (v is int) return (T)(object)(double)(int)v;
			if (v is double) return (T)v;
			if (v is float) return (T)(object)(double)(float)v;
		}
		if (typeof(T) == typeof(float)) {
			if (v is int) return (T)(object)(float)(int)v;
			if (v is double) return (T)(object)(float)(double)v;
			if (v is float) return (T)v;
		}
		if (v is System.Collections.Generic.IDictionary<object, object> dm) {
			var m = new Dictionary<string, object>();
			foreach (var kv in dm) m[Convert.ToString(kv.Key)] = kv.Value;
			v = m;
		}
		var json = JsonSerializer.Serialize(v);
		return JsonSerializer.Deserialize<T>(json);
	}
	
}
