// Generated by Mochi 0.10.59 on 2025-08-06 22:16 +0700
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Numerics;
using System.Collections;

class Program {
    static bool seededNow = false;
    static long nowSeed = 0;
    static long _now() {
        if (!seededNow) {
            var s = Environment.GetEnvironmentVariable("MOCHI_NOW_SEED");
            if (long.TryParse(s, out var v)) {
                nowSeed = v;
                seededNow = true;
            }
        }
        if (seededNow) {
            nowSeed = unchecked(nowSeed * 1664525 + 1013904223);
            nowSeed %= 9223372036854775783L;
            if (nowSeed < 0) nowSeed += 9223372036854775783L;
            return nowSeed;
        }
        return DateTime.UtcNow.Ticks / 100;
    }
    static long _mem() {
        return GC.GetTotalAllocatedBytes(true);
    }
    static string _substr(string s, long start, long end) {
        if (start < 0) start = 0;
        if (end < 0) end = 0;
        if (start > s.Length) start = s.Length;
        if (end > s.Length) end = s.Length;
        if (start > end) start = end;
        return s.Substring((int)start, (int)(end - start));
    }
    static string _fmt(object v) {
        if (v is Array a) {
            var parts = new List<string>();
            foreach (var x in a) parts.Add(_fmt(x));
            return "[" + string.Join(", ", parts) + "]";
        }
        if (v is System.Collections.IDictionary d) {
            var keys = new List<string>();
            foreach (var k in d.Keys) keys.Add(k.ToString());
            keys.Sort();
            var parts = new List<string>();
            foreach (var k in keys) parts.Add(k + ":" + _fmt(d[k]));
            return "map[" + string.Join(", ", parts) + "]";
        }
        if (v is System.Collections.IEnumerable e && !(v is string)) {
            var parts = new List<string>();
            foreach (var x in e) parts.Add(_fmt(x));
            return string.Join(", ", parts);
        }
        if (v is string s) return "\"" + s.Replace("\"", "\\\"") + "\"";
        if (v is bool b) return b ? "true" : "false";
        return Convert.ToString(v);
    }
    static string _fmtStr(object v) {
        if (v is Array a) {
            var parts = new List<string>();
            foreach (var x in a) parts.Add(_fmtStr(x));
            return "[" + string.Join(" ", parts) + "]";
        }
        if (v is System.Collections.IDictionary d) {
            var keys = new List<string>();
            foreach (var k in d.Keys) keys.Add(k.ToString());
            keys.Sort();
            var parts = new List<string>();
            foreach (var k in keys) parts.Add(k + ":" + _fmtStr(d[k]));
            return "map[" + string.Join(" ", parts) + "]";
        }
        if (v is System.Collections.IEnumerable e && !(v is string)) {
            var parts = new List<string>();
            foreach (var x in e) parts.Add(_fmtStr(x));
            return string.Join(" ", parts);
        }
        if (v is string s) return "\"" + s.Replace("\"", "\\\"") + "\"";
        if (v is bool b) return b ? "true" : "false";
        return Convert.ToString(v);
    }
    public static string _fmtTop(object v) {
        if (v is Array a && a.Length > 0 && a.GetValue(0) is Array) {
            var parts = new List<string>();
            foreach (var x in a) parts.Add(_fmt(x));
            return string.Join(" ", parts);
        }
        if (v is string s) return s;
        return _fmt(v);
    }
    static long[] arr_11 = new long[]{0, 0, 0, 0, 0};
    public static long[] zeros(long n_0) {
        long[] res_1 = new long[]{};
        long i_2 = 0;
        while ((i_2 < n_0)) {
            res_1 = (Enumerable.ToArray(Enumerable.Append<long>(res_1, 0)));
            i_2 = (i_2 + 1);
        };
        return res_1;
    }

    public static void update(long[] arr_3, long idx_4, long value_5) {
        arr_3[idx_4] = value_5;
    }

    public static long query(long[] arr_6, long left_7, long right_8) {
        long result_9 = 0;
        long i_10 = left_7;
        while ((i_10 < right_8)) {
            if ((arr_6[(int)(i_10)] > result_9)) {
                result_9 = arr_6[(int)(i_10)];
            }
            i_10 = (i_10 + 1);
        };
        return result_9;
    }

    static void Main() {
        {
            var __memStart = _mem();
            var __start = _now();
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 0, 5)));
            Program.update(arr_11, 4, 100);
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 0, 5)));
            Program.update(arr_11, 4, 0);
            Program.update(arr_11, 2, 20);
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 0, 5)));
            Program.update(arr_11, 4, 10);
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 2, 5)));
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 1, 5)));
            Program.update(arr_11, 2, 0);
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 0, 5)));
            arr_11 = Program.zeros(10000);
            Program.update(arr_11, 255, 30);
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 0, 10000)));
            arr_11 = Program.zeros(6);
            Program.update(arr_11, 5, 1);
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 5, 6)));
            arr_11 = Program.zeros(6);
            Program.update(arr_11, 0, 1000);
            Console.WriteLine(Program._fmtTop(Program.query(arr_11, 0, 1)));
            var __end = _now();
            var __memEnd = _mem();
            var __dur = (__end - __start);
            if (__dur <= 0) __dur = 1;
            var __memDiff = __memEnd - __memStart;
            if (__memDiff <= 0) __memDiff = __memEnd;
            Console.WriteLine("{\"name\":\"main\",\"duration_us\":" + __dur + ",\"memory_bytes\":" + __memDiff + "}");
        }
    }
}
