! Generated by Mochi transpiler v0.10.31 on 2025-07-19 19:53:35 GMT+7
program main
  integer :: x = 12
  character(len=100) :: msg
  if ((x > 10)) then
  msg = "yes"
  else
  msg = "no"
  end if
  print *, trim(msg)
end program main
