// Generated by Mochi compiler v0.10.26 on 1970-01-01T00:00:00Z
// Source: /workspace/mochi/tests/vm/valid/cast_struct.mochi

type Todo = {
  title: string;
};

let todo: Todo;

function main(): void {
  todo = { "title": "hi" } as Todo;
  _print(todo.title);
}
function _print(...args: any[]): void {
  const out = args.map((a) => {
    if (Array.isArray(a)) return a.join(" ");
    if (a && typeof a === "object") return JSON.stringify(a);
    return String(a);
  }).join(" ").trimEnd();
  console.log(out);
}

main();
