// Generated by Mochi compiler v0.10.27 on 1970-01-01T00:00:00Z
// Source: /workspace/mochi/tests/vm/valid/map_int_key.mochi

let m: { [key: number]: string };

function main(): void {
  m = {
    [1]: "a",
    [2]: "b",
  };
  _print(m[1]);
}
function _print(...args: any[]): void {
  const out = args.map((a) => {
    if (Array.isArray(a)) return a.map(_p).join(" ");
    return _p(a);
  }).join(" ").trimEnd();
  console.log(out);
}
function _p(a: any): string {
  if (typeof a === "boolean") return a ? "1" : "0";
  if (typeof a === "number") {
    if (Number.isInteger(a)) return String(a);
    return Number(a).toPrecision(6);
  }
  return String(a);
}

main();
