// Generated by Mochi TypeScript compiler

function outer(x: number): number {
  function inner(y: number): number {
    return (x + y);
  }
  return inner(5);
}

function main(): void {
  console.log(outer(3));
}
main();
