// Generated by Mochi compiler v0.10.27 on 1970-01-01T00:00:00Z
// Source: /workspace/mochi/tests/vm/valid/python_auto.mochi

const math = {
  pi: Math.PI,
  e: Math.E,
  sqrt: Math.sqrt,
  pow: Math.pow,
  sin: Math.sin,
  log: Math.log,
};

function main(): void {
  _print(math.sqrt(16));
  _print(math.pi);
}
function _print(...args: any[]): void {
  const out = args.map((a) => {
    if (Array.isArray(a)) return a.join(" ");
    if (typeof a === "boolean") return String(a);
    if (a && typeof a === "object") return "[object Object]";
    if (typeof a === "number") {
      let s = String(a);
      if (/\.\d{6,}/.test(s)) {
        s = Number(a.toFixed(6)).toString();
      }
      return s;
    }
    return String(a);
  }).join(" ").trimEnd();
  console.log(out);
}

main();
