// Generated by Mochi compiler v0.10.27 on 1970-01-01T00:00:00Z
// Source: /workspace/mochi/tests/vm/valid/string_in_operator.mochi

let s: string;

function main(): void {
  s = "catch";
  _print(s.includes("cat") ? 1 : 0);
  _print(s.includes("dog") ? 1 : 0);
}
function _print(...args: any[]): void {
  const out = args.map((a) => {
    if (Array.isArray(a)) return a.join(" ");
    return String(a);
  }).join(" ").trimEnd();
  console.log(out);
}

main();
