package sandbox

// Extensions maps language to file extension used for hello world programs.
var Extensions = map[string]string{
    "go": "go",
    "py": "py",
    "ts": "ts",
    "asm": "asm",
    "c": "c",
    "clj": "clj",
    "cobol": "cob",
    "cpp": "cpp",
    "cs": "cs",
    "dart": "dart",
    "erlang": "erl",
    "ex": "exs",
    "fortran": "f90",
    "fs": "fs",
    "hs": "hs",
    "java": "java",
    "jvm": "jvm",
    "kt": "kt",
    "lua": "lua",
    "mlir": "mlir",
    "ocaml": "ml",
    "pas": "pas",
    "php": "php",
    "pl": "pl",
    "rb": "rb",
    "rkt": "rkt",
    "rust": "rs",
    "scala": "scala",
    "scheme": "scm",
    "st": "st",
    "swift": "swift",
    "wasm": "wat",
    "zig": "zig",
}

// RunCmds provides commands to execute the hello world program for a language.
var RunCmds = map[string][]string{
    "go": {"go", "run", "hello.go"},
    "py": {"python", "hello.py"},
    "ts": {"bash", "-c", "tsc hello.ts && node hello.js"},
    "asm": {"bash", "-c", "gcc hello.asm -o hello && ./hello"},
    "c": {"bash", "-c", "gcc hello.c -o hello && ./hello"},
    "clj": {"clojure", "hello.clj"},
    "cobol": {"bash", "-c", "cobc -x hello.cob && ./hello"},
    "cpp": {"bash", "-c", "g++ hello.cpp -o hello && ./hello"},
    "cs": {"bash", "-c", "mcs hello.cs && mono hello.exe"},
    "dart": {"dart", "hello.dart"},
    "erlang": {"escript", "hello.erl"},
    "ex": {"elixir", "hello.exs"},
    "fortran": {"bash", "-c", "gfortran hello.f90 -o hello && ./hello"},
    "fs": {"dotnet", "fsi", "hello.fs"},
    "hs": {"runhaskell", "hello.hs"},
    "java": {"bash", "-c", "javac hello.java && java hello"},
    "jvm": {"bash", "-c", "javac hello.jvm && java HelloJvm"},
    "kt": {"bash", "-c", "kotlinc hello.kt -include-runtime -d hello.jar && java -jar hello.jar"},
    "lua": {"lua", "hello.lua"},
    "mlir": {"bash", "-c", "cat hello.mlir"},
    "ocaml": {"ocaml", "hello.ml"},
    "pas": {"bash", "-c", "fpc hello.pas && ./hello"},
    "php": {"php", "hello.php"},
    "pl": {"perl", "hello.pl"},
    "rb": {"ruby", "hello.rb"},
    "rkt": {"racket", "hello.rkt"},
    "rust": {"bash", "-c", "rustc hello.rs -o hello && ./hello"},
    "scala": {"bash", "-c", "scalac hello.scala && scala Hello"},
    "scheme": {"bash", "-c", "scheme --script hello.scm"},
    "st": {"bash", "-c", "echo hello"},
    "swift": {"bash", "-c", "swiftc hello.swift -o hello && ./hello"},
    "wasm": {"bash", "-c", "wat2wasm hello.wat -o hello.wasm && wasmtime hello.wasm"},
    "zig": {"zig", "run", "hello.zig"},
}
