;; Generated on 2025-07-20 22:17 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define (boom)
   (begin (display "boom")
     (newline)
     "true")
  )
(display (and (and (< 1 2)
       (< 2 3)
      )
     (< 3 4)
    )
  )
(newline)
(display (and (and (< 1 2)
       (> 2 3)
      )
     (boom)
    )
  )
(newline)
(display (and (and (and (< 1 2)
         (< 2 3)
        )
       (> 3 4)
      )
     (boom)
    )
  )
(newline)
