;; Generated on 2025-07-21 17:26 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define (boom)
   (begin (display "boom")
     (newline)
     "true")
  )
(display (if (and (and (< 1 2)
         (< 2 3)
        )
       (< 3 4)
      )
     1 0)
  )
(newline)
(display (if (and (and (< 1 2)
         (> 2 3)
        )
       (boom)
      )
     1 0)
  )
(newline)
(display (if (and (and (and (< 1 2)
           (< 2 3)
          )
         (> 3 4)
        )
       (boom)
      )
     1 0)
  )
(newline)
