;; Generated on 2025-07-20 15:06 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define numbers (list 1 2 3 4 5 6 7 8 9)
  )
(let/ec break2 (let loop1 ((it3 numbers)
      )
     (if (null? it3)
       (quote nil)
       (let ((n (car it3)
            )
          )
         (begin (if (= (modulo n 2)
               0)
             (begin (loop1)
              )
             (quote nil)
            )
           (if (> n 7)
             (begin (break2)
              )
             (quote nil)
            )
           (display "odd number:")
           (display " ")
           (display n)
           (newline)
           (loop1 (cdr it3)
            )
          )
        )
      )
    )
  )
