;; Generated on 2025-07-21 17:26 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define numbers (list 1 2 3 4 5 6 7 8 9)
  )
(let/ec break2 (letrec ((loop1 (lambda (xs)
           (if (null? xs)
             (quote nil)
             (begin (let ((n (car xs)
                    )
                  )
                 (begin (if (= (modulo n 2)
                       0)
                     (begin (loop1 (cdr xs)
                        )
                      )
                     (quote nil)
                    )
                   (if (> n 7)
                     (begin (break2)
                      )
                     (quote nil)
                    )
                   (display "odd number:")
                   (display " ")
                   (display n)
                   (newline)
                  )
                )
               (loop1 (cdr xs)
                )
              )
            )
          )
        )
      )
     (loop1 numbers)
    )
  )
