;; Generated on 2025-07-20 22:17 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define nums (list 1 2 3)
  )
(define letters (list "A" "B")
  )
(define pairs (let ((res4 (list)
        )
      )
     (begin (for-each (lambda (n)
           (for-each (lambda (l)
               (if (= (modulo n 2)
                   0)
                 (set! res4 (append res4 (list (alist->hash-table (list (cons "n" n)
                           (cons "l" l)
                          )
                        )
                      )
                    )
                  )
                 (quote nil)
                )
              )
             letters)
          )
         nums)
       res4)
    )
  )
(display "--- Even pairs ---")
(newline)
(for-each (lambda (p)
     (begin (display (hash-table-ref p "n")
        )
       (display " ")
       (display (hash-table-ref p "l")
        )
       (newline)
      )
    )
   pairs)
