;; Generated on 2025-07-20 17:38 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define customers (list (alist->hash-table (list (cons "id" 1)
         (cons "name" "Alice")
        )
      )
     (alist->hash-table (list (cons "id" 2)
         (cons "name" "Bob")
        )
      )
     (alist->hash-table (list (cons "id" 3)
         (cons "name" "Charlie")
        )
      )
    )
  )
(define orders (list (alist->hash-table (list (cons "id" 100)
         (cons "customerId" 1)
         (cons "total" 250)
        )
      )
     (alist->hash-table (list (cons "id" 101)
         (cons "customerId" 2)
         (cons "total" 125)
        )
      )
     (alist->hash-table (list (cons "id" 102)
         (cons "customerId" 1)
         (cons "total" 300)
        )
      )
    )
  )
(define result (let ((res1 (list)
        )
      )
     (begin (for-each (lambda (o)
           (for-each (lambda (c)
               (set! res1 (append res1 (list (alist->hash-table (list (cons "orderId" (hash-table-ref o "id")
                          )
                         (cons "orderCustomerId" (hash-table-ref o "customerId")
                          )
                         (cons "pairedCustomerName" (hash-table-ref c "name")
                          )
                         (cons "orderTotal" (hash-table-ref o "total")
                          )
                        )
                      )
                    )
                  )
                )
              )
             customers)
          )
         orders)
       res1)
    )
  )
(display "--- Cross Join: All order-customer pairs ---")
(newline)
(for-each (lambda (entry)
     (begin (display "Order")
       (display " ")
       (display (hash-table-ref entry "orderId")
        )
       (display " ")
       (display "(customerId:")
         (display " ")
         (display (hash-table-ref entry "orderCustomerId")
          )
         (display " ")
         (display ", total: $")
         (display " ")
         (display (hash-table-ref entry "orderTotal")
          )
         (display " ")
         (display ")
         paired with")
       (display " ")
       (display (hash-table-ref entry "pairedCustomerName")
        )
       (newline)
      )
    )
   result)
