;; Generated on 2025-07-21 06:54 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define data (list 1 2)
  )
(define flag (if (null? (let ((res1 (list)
            )
          )
         (begin (for-each (lambda (x)
               (if (= x 1)
                 (set! res1 (append res1 (list x)
                    )
                  )
                 (quote nil)
                )
              )
             data)
           res1)
        )
      )
     "false" "true")
  )
(display flag)
(newline)
