;; Generated on 2025-07-21 13:50 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define people (list (alist->hash-table (list (cons "name" "Alice")
         (cons "age" 30)
         (cons "city" "Paris")
        )
      )
     (alist->hash-table (list (cons "name" "Bob")
         (cons "age" 15)
         (cons "city" "Hanoi")
        )
      )
     (alist->hash-table (list (cons "name" "Charlie")
         (cons "age" 65)
         (cons "city" "Paris")
        )
      )
     (alist->hash-table (list (cons "name" "Diana")
         (cons "age" 45)
         (cons "city" "Hanoi")
        )
      )
     (alist->hash-table (list (cons "name" "Eve")
         (cons "age" 70)
         (cons "city" "Paris")
        )
      )
     (alist->hash-table (list (cons "name" "Frank")
         (cons "age" 22)
         (cons "city" "Hanoi")
        )
      )
    )
  )
(define stats (let ((groups2 (make-hash-table)
        )
       (res5 (list)
        )
      )
     (begin (for-each (lambda (person)
           (let* ((k4 (hash-table-ref person "city")
                )
               (g3 (hash-table-ref/default groups2 k4 #f)
                )
              )
             (begin (if (not g3)
                 (begin (set! g3 (alist->hash-table (list (cons "key" k4)
                         (cons "items" (list)
                          )
                        )
                      )
                    )
                   (hash-table-set! groups2 k4 g3)
                  )
                 (quote nil)
                )
               (hash-table-set! g3 "items" (append (hash-table-ref g3 "items")
                   (list person)
                  )
                )
              )
            )
          )
         people)
       (for-each (lambda (g)
           (set! res5 (append res5 (list (alist->hash-table (list (cons "city" (hash-table-ref g "key")
                      )
                     (cons "count" (cond ((string? g)
                           (string-length g)
                          )
                         ((hash-table? g)
                           (hash-table-size g)
                          )
                         (else (length g)
                          )
                        )
                      )
                     (cons "avg_age" (let ((xs (let ((res1 (list)
                                  )
                                )
                               (begin (for-each (lambda (p)
                                     (set! res1 (append res1 (list (hash-table-ref p "age")
                                          )
                                        )
                                      )
                                    )
                                   (hash-table-ref g "items")
                                  )
                                 res1)
                              )
                            )
                          )
                         (exact->inexact (/ (apply + xs)
                             (length xs)
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
         (hash-table-values groups2)
        )
       res5)
    )
  )
(display "--- People grouped by city ---")
(newline)
(for-each (lambda (s)
     (begin (display (hash-table-ref s "city")
        )
       (display " ")
       (display ": count =")
       (display " ")
       (display (hash-table-ref s "count")
        )
       (display " ")
       (display ", avg_age =")
       (display " ")
       (display (hash-table-ref s "avg_age")
        )
       (newline)
      )
    )
   stats)
