;; Generated on 2025-07-20 22:17 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define xs (list 1 2 3)
  )
(define ys (let ((res34 (list)
        )
      )
     (begin (for-each (lambda (x)
           (if (= (modulo x 2)
               1)
             (set! res34 (append res34 (list x)
                )
              )
             (quote nil)
            )
          )
         xs)
       res34)
    )
  )
(display (cond ((string? ys)
       (if (string-contains ys 1)
         "true" "false")
      )
     ((hash-table? ys)
       (if (hash-table-exists? ys 1)
         "true" "false")
      )
     (else (if (member 1 ys)
         "true" "false")
      )
    )
  )
(newline)
(display (cond ((string? ys)
       (if (string-contains ys 2)
         "true" "false")
      )
     ((hash-table? ys)
       (if (hash-table-exists? ys 2)
         "true" "false")
      )
     (else (if (member 2 ys)
         "true" "false")
      )
    )
  )
(newline)
(define m (alist->hash-table (list (cons "a" 1)
      )
    )
  )
(display (cond ((string? m)
       (if (string-contains m "a")
         "true" "false")
      )
     ((hash-table? m)
       (if (hash-table-exists? m "a")
         "true" "false")
      )
     (else (if (member "a" m)
         "true" "false")
      )
    )
  )
(newline)
(display (cond ((string? m)
       (if (string-contains m "b")
         "true" "false")
      )
     ((hash-table? m)
       (if (hash-table-exists? m "b")
         "true" "false")
      )
     (else (if (member "b" m)
         "true" "false")
      )
    )
  )
(newline)
(define s "hello")
(display (cond ((string? s)
       (if (string-contains s "ell")
         "true" "false")
      )
     ((hash-table? s)
       (if (hash-table-exists? s "ell")
         "true" "false")
      )
     (else (if (member "ell" s)
         "true" "false")
      )
    )
  )
(newline)
(display (cond ((string? s)
       (if (string-contains s "foo")
         "true" "false")
      )
     ((hash-table? s)
       (if (hash-table-exists? s "foo")
         "true" "false")
      )
     (else (if (member "foo" s)
         "true" "false")
      )
    )
  )
(newline)
