;; Generated on 2025-07-20 22:17 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define customers (list (alist->hash-table (list (cons "id" 1)
         (cons "name" "Alice")
        )
      )
     (alist->hash-table (list (cons "id" 2)
         (cons "name" "Bob")
        )
      )
     (alist->hash-table (list (cons "id" 3)
         (cons "name" "Charlie")
        )
      )
    )
  )
(define orders (list (alist->hash-table (list (cons "id" 100)
         (cons "customerId" 1)
         (cons "total" 250)
        )
      )
     (alist->hash-table (list (cons "id" 101)
         (cons "customerId" 2)
         (cons "total" 125)
        )
      )
     (alist->hash-table (list (cons "id" 102)
         (cons "customerId" 1)
         (cons "total" 300)
        )
      )
     (alist->hash-table (list (cons "id" 103)
         (cons "customerId" 4)
         (cons "total" 80)
        )
      )
    )
  )
(define result (let ((res35 (list)
        )
      )
     (begin (for-each (lambda (o)
           (for-each (lambda (c)
               (if (= (hash-table-ref o "customerId")
                   (hash-table-ref c "id")
                  )
                 (set! res35 (append res35 (list (alist->hash-table (list (cons "orderId" (hash-table-ref o "id")
                            )
                           (cons "customerName" (hash-table-ref c "name")
                            )
                           (cons "total" (hash-table-ref o "total")
                            )
                          )
                        )
                      )
                    )
                  )
                 (quote nil)
                )
              )
             customers)
          )
         orders)
       res35)
    )
  )
(display "--- Orders with customer info ---")
(newline)
(for-each (lambda (entry)
     (begin (display "Order")
       (display " ")
       (display (hash-table-ref entry "orderId")
        )
       (display " ")
       (display "by")
       (display " ")
       (display (hash-table-ref entry "customerName")
        )
       (display " ")
       (display "- $")
       (display " ")
       (display (hash-table-ref entry "total")
        )
       (newline)
      )
    )
   result)
