;; Generated on 2025-07-20 14:31 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define x 3)
(define y 4)
(define m (alist->hash-table (list (cons "a" x)
       (cons "b" y)
      )
    )
  )
(display (hash-table-ref m "a")
  )
(display " ")
(display (hash-table-ref m "b")
  )
(newline)
