;; Generated on 2025-07-20 22:17 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define (outer x)
   (begin (define (inner y)
       (string-append "x" "y")
      )
     (inner 5)
    )
  )
(display (outer 3)
  )
(newline)
