;; Generated on 2025-07-20 22:17 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define (boom a b)
   (begin (display "boom")
     (newline)
     "true")
  )
(display (and "false" (boom 1 2)
    )
  )
(newline)
(display (or "true" (boom 1 2)
    )
  )
(newline)
