;; Generated on 2025-07-20 22:17 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define items (list (alist->hash-table (list (cons "n" 1)
         (cons "v" "a")
        )
      )
     (alist->hash-table (list (cons "n" 1)
         (cons "v" "b")
        )
      )
     (alist->hash-table (list (cons "n" 2)
         (cons "v" "c")
        )
      )
    )
  )
(define result (let ((res49 (list)
        )
      )
     (begin (for-each (lambda (i)
           (set! res49 (append res49 (list (hash-table-ref i "v")
                )
              )
            )
          )
         items)
       res49)
    )
  )
(display result)
(newline)
