;; Generated on 2025-07-21 17:26 +0700
(import (srfi 1) (srfi 69) (chibi string))
(display (if (string<? "a" "b")
     1 0)
  )
(newline)
(display (if (string<=? "a" "a")
     1 0)
  )
(newline)
(display (if (string>? "b" "a")
     1 0)
  )
(newline)
(display (if (string>=? "b" "b")
     1 0)
  )
(newline)
