;; Generated on 2025-07-20 16:45 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define s "catch")
(display (if (string-contains s "cat")
     "true" "false")
  )
(newline)
(display (if (string-contains s "dog")
     "true" "false")
  )
(newline)
