;; Generated on 2025-07-21 17:26 +0700
(import (srfi 1) (srfi 69) (chibi string))
(define prefix "fore")
(define s1 "forest")
(display (if (= (substring s1 0 (string-length prefix)
        )
       prefix)
     1 0)
  )
(newline)
(define s2 "desert")
(display (if (= (substring s2 0 (string-length prefix)
        )
       prefix)
     1 0)
  )
(newline)
