;; Generated by Mochi transpiler on 2025-07-19T13:13:34Z
(import (srfi 1))
(define prefix "fore")
(define s1 "forest")
(display (if (equal? (if (string? s1) (substring s1 0 (if (string? prefix) (string-length prefix) (length prefix))) (take (drop s1 0) (- (if (string? prefix) (string-length prefix) (length prefix)) 0))) prefix) 1 0))
(newline)
(define s2 "desert")
(display (if (equal? (if (string? s2) (substring s2 0 (if (string? prefix) (string-length prefix) (length prefix))) (take (drop s2 0) (- (if (string? prefix) (string-length prefix) (length prefix)) 0))) prefix) 1 0))
(newline)
