;; Generated on 2025-07-22 10:01 +0700
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define x 0)
(display (to-str x)
)
(newline)
