;; Generated on 2025-07-20 22:46 +0700
(import (srfi 1) (srfi 69) (srfi 95) (chibi string))
(define m (alist->hash-table (list (cons "a" 1)
       (cons "b" 2)
       (cons "c" 3)
      )
    )
  )
(display (string-join (map number->string (sort (hash-table-values m)
         <)
      )
     " ")
  )
(newline)
