       IDENTIFICATION DIVISION.
       PROGRAM-ID. LEN_STRING.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 TMP PIC 9 VALUE 0.
       PROCEDURE DIVISION.
       DISPLAY FUNCTION LENGTH("mochi")
       STOP RUN.
