       IDENTIFICATION DIVISION.
       PROGRAM-ID. LET_AND_PRINT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 A PIC 9 VALUE 10.
       01 B PIC 9 VALUE 20.
       PROCEDURE DIVISION.
       DISPLAY A + B
       STOP RUN.
