       IDENTIFICATION DIVISION.
       PROGRAM-ID. MAP_LITERAL_DYNAMIC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 X PIC 9 VALUE 3.
       01 Y PIC 9 VALUE 4.
       01 TMP PIC 9(9) VALUE 0.
       PROCEDURE DIVISION.
       COMPUTE TMP = X
       COMPUTE TMP = Y
       DISPLAY TMP TMP
       STOP RUN.
