       IDENTIFICATION DIVISION.
       PROGRAM-ID. PURE-FOLD.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 FN-TRIPLE-RES PIC 9 VALUE 0.
       01 TMP PIC 9(9) VALUE 0.
       PROCEDURE DIVISION.
       COMPUTE TMP = 1 + 2
       PERFORM FN_TRIPLE USING TMP
       DISPLAY FN_TRIPLE_RES
       STOP RUN.
       
       FN_TRIPLE.
           PROCEDURE DIVISION USING X.
               COMPUTE FN_TRIPLE_RES = X * 3
               EXIT.
