       IDENTIFICATION DIVISION.
       PROGRAM-ID. STR_BUILTIN.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 TMP PIC 9 VALUE 0.
       PROCEDURE DIVISION.
       PERFORM STR USING 123
       DISPLAY STR_RES
       STOP RUN.
