       IDENTIFICATION DIVISION.
       PROGRAM-ID. STRING_INDEX.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 S PIC X(5) VALUE "mochi".
       01 TMP PIC 9 VALUE 0.
       PROCEDURE DIVISION.
       DISPLAY S(2:1)
       STOP RUN.
