//go:build slow

package pl_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	pl "mochi/compiler/x/pl"
	"mochi/parser"
	"mochi/types"
)

func repoRoot(t *testing.T) string {
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 10; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatal("go.mod not found")
	return ""
}

func shouldUpdateRosetta() bool {
	if v, ok := os.LookupEnv("UPDATE"); ok && (v == "1" || v == "true") {
		return true
	}
	return false
}

func stripHeaderRosetta(b []byte) []byte {
	if i := bytes.IndexByte(b, '\n'); i != -1 && bytes.HasPrefix(b, []byte("% Generated by Mochi")) {
		return b[i+1:]
	}
	return b
}

func runRosettaTaskGolden(t *testing.T, name string) {
	root := repoRoot(t)
	script := exec.Command("go", "run", "-tags=archive,slow", "./scripts/compile_rosetta_pl.go")
	script.Env = append(os.Environ(), "TASKS="+name)
	script.Dir = root
	if out, err := script.CombinedOutput(); err != nil {
		t.Fatalf("compile script error: %v\n%s", err, out)
	}
	errFile := filepath.Join(root, "tests", "rosetta", "out", "Prolog", name+".error")
	if b, err := os.ReadFile(errFile); err == nil {
		t.Skipf("prolog run failed:\n%s", b)
		return
	}
	src := filepath.Join(root, "tests", "rosetta", "x", "Mochi", name+".mochi")
	prog, err := parser.Parse(src)
	if err != nil {
		t.Fatalf("parse error: %v", err)
	}
	env := types.NewEnv(nil)
	if errs := types.Check(prog, env); len(errs) > 0 {
		t.Fatalf("type error: %v", errs[0])
	}
	code, err := pl.New(env).Compile(prog)
	if err != nil {
		t.Fatalf("compile error: %v", err)
	}
	codeWant := filepath.Join(root, "tests", "rosetta", "out", "Prolog", name+".pl")
	if shouldUpdateRosetta() {
		_ = os.WriteFile(codeWant, code, 0o644)
	} else if want, err := os.ReadFile(codeWant); err == nil {
		got := stripHeaderRosetta(bytes.TrimSpace(code))
		want = stripHeaderRosetta(bytes.TrimSpace(want))
		if !bytes.Equal(got, want) {
			t.Errorf("generated code mismatch for %s.pl\n\n--- Got ---\n%s\n\n--- Want ---\n%s", name, got, want)
		}
	}
	dir := t.TempDir()
	file := filepath.Join(dir, "main.pl")
	if err := os.WriteFile(file, code, 0o644); err != nil {
		t.Fatalf("write error: %v", err)
	}
	out, err := exec.Command("swipl", "-q", "-s", file, "-t", "halt").CombinedOutput()
	if err != nil {
		t.Fatalf("swipl error: %v\n%s", err, out)
	}
	gotOut := bytes.ReplaceAll(bytes.TrimSpace(out), []byte(" "), nil)
	outWant := filepath.Join(root, "tests", "rosetta", "out", "Prolog", name+".out")
	if shouldUpdateRosetta() {
		_ = os.WriteFile(outWant, append(gotOut, '\n'), 0o644)
	} else if wantOut, err := os.ReadFile(outWant); err == nil {
		wantNorm := bytes.ReplaceAll(bytes.TrimSpace(wantOut), []byte(" "), nil)
		if !bytes.Equal(gotOut, wantNorm) {
			t.Errorf("output mismatch for %s.out\n\n--- Got ---\n%s\n\n--- Want ---\n%s", name, gotOut, wantNorm)
		}
	}
}

func TestPrologCompiler_Rosetta_Golden(t *testing.T) {
	if _, err := exec.LookPath("swipl"); err != nil {
		t.Skip("swipl not installed")
	}
	root := repoRoot(t)
	files, err := filepath.Glob(filepath.Join(root, "tests", "rosetta", "x", "Mochi", "*.mochi"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	max := 1
	if len(files) < max {
		max = len(files)
	}
	for _, f := range files[:max] {
		name := strings.TrimSuffix(filepath.Base(f), ".mochi")
		t.Run(name, func(t *testing.T) { runRosettaTaskGolden(t, name) })
	}
}
