// Generated by Mochi v0.10.38 on 2025-07-23 17:01:25 GMT+7

let door: number = 1;
let incrementer: number = 0;
for (let current = 1; current < 101; current++) {
  let line = (("Door " + String(current)) + " ");
  if ((current == door)) {
    line = (line + "Open");
    incrementer = (incrementer + 1);
    door = ((door + (2 * incrementer)) + 1);
  } else {
    line = (line + "Closed");
  }
  console.log(line);
}
