// Generated by Mochi v0.10.36 on 2025-07-22 17:44:30 GMT+7

let doors: any[] = [];
for (let i = 0; i < 100; i++) {
  doors = [...doors, false];
}
for (let pass = 1; pass < 101; pass++) {
  let idx = (pass - 1);
  while ((idx < 100)) {
    doors[idx] = !doors[idx];
    idx = (idx + pass);
  }
}
for (let row = 0; row < 10; row++) {
  let line = "";
  for (let col = 0; col < 10; col++) {
    const idx = ((row * 10) + col);
    if (doors[idx]) {
      line = (line + "1");
    } else {
      line = (line + "0");
    }
    if ((col < 9)) {
      line = (line + " ");
    }
  }
  console.log(line);
}
