// Generated by Mochi transpiler v0.10.31 on 2025-07-19 13:30:33 GMT+7
object Main {
    def main(args: Array[String]): Unit = {
        println(6 * 7)
        println(7 / 2)
        println(7 % 2)
    }
}
