// Generated by Mochi v0.10.31 on 2025-07-20 15:33:24 GMT+7
import scala.collection.mutable.{ArrayBuffer, Map}
object Main {
  def sum_rec(n: Int, acc: Int): Int = {
    if (n == 0) {
    return acc
  }
    return sum_rec(n - 1, acc + n)
  }

  def main(args: Array[String]): Unit = {
    println(sum_rec(10, 0))
  }
}
