// Generated by Mochi transpiler v0.10.31 on 2025-07-20 08:42 +0700
fn main() {
    println!("{}", format!("{:.1}", { let tmp = vec![1, 2, 3]; tmp.iter().map(|x| *x as f64).sum::<f64>() / (tmp.len() as f64) }));
}
