// Generated by Mochi transpiler v0.10.31 on 2025-07-20 08:42 +0700
fn main() {
    let nums: Vec<i64> = vec![3, 1, 4];
    println!("{}", { let tmp = nums.clone(); *tmp.iter().min().unwrap_or(&0) });
    println!("{}", { let tmp = nums.clone(); *tmp.iter().max().unwrap_or(&0) });
}
