// Generated by Mochi v0.10.32 on 2025-07-21 11:02:38 GMT+7

function boom(): boolean {
  console.log(["boom"].join(' ').trimEnd());
  return true;
}
console.log([+(((1 < 2) && (2 < 3)) && (3 < 4))].join(' ').trimEnd());
console.log([+(((1 < 2) && (2 > 3)) && boom())].join(' ').trimEnd());
console.log([+((((1 < 2) && (2 < 3)) && (3 > 4)) && boom())].join(' ').trimEnd());
