// Generated by Mochi v0.10.32 on 2025-07-21 07:25:18 GMT+7

interface Customer { id: number; name: string };
interface Order { id: number; customerId: number };
interface Result { name: any; count: number };
const customers: Customer[] = [{id: 1, name: "Alice"}, {id: 2, name: "Bob"}];
const orders: Order[] = [{id: 100, customerId: 1}, {id: 101, customerId: 1}, {id: 102, customerId: 2}];
const stats: Result[] = (() => {
  let _items = orders.map(v => [v])
  { const _joined = []
    const _arr = customers
    for (const _left of _items) {
      const [o] = _left;
      let _m = false;
      for (let _ri=0; _ri < _arr.length; _ri++) {
        const c = _arr[_ri];
        if (!((o["customerId"] == c["id"]))) continue;
        _m = true; _joined.push([..._left, c]) }
    }
    _items = _joined;
  }
  let _rows = _items
  const result: Result[] = []
  for (const r of _rows) { const [o, c] = r; result.push({name: g["key"], count: (Array.isArray(g) || typeof g === 'string' ? g.length : Object.keys(g ?? {}).length)}) }
  return result
})();
console.log("--- Orders per customer ---");
for (const s of stats) {
  console.log(s["name"], "orders:", s["count"]);
}
