// Generated by Mochi v0.10.33 on 2025-07-21 16:20:46 GMT+7

export interface Data { outer: Record<string, number> }
let data: Data = {"outer": {"inner": 1}};
data["outer"]["inner"] = 2;
console.log([data["outer"]["inner"]].map(v=>v===null?'nil':typeof v==='object'?JSON.stringify(v).replace(/:/g, ': ').replace(/,/g, ', '):v).join(' ').trimEnd());
