// Generated by Mochi v0.10.31 on 2025-07-19 19:39:35 GMT+7
function __len(v:any):number {
  if (Array.isArray(v) || typeof v==='string') return v.length;
  return Object.keys(v||{}).length;
}
function __print(...args:any[]) {
  const out:string[]=[];
  for (const a of args) {
    if (typeof a==='boolean') out.push(a? '1':'0');
    else if (Array.isArray(a)) out.push(a.map(x=>typeof x==='boolean'? (x?'1':'0'):String(x)).join(' '));
    else out.push(String(a));
  }
  console.log(out.join(' '));
}
let s = "catch";

__print(("cat" in s));

__print(("dog" in s));
