// Generated by Mochi v0.10.34 on 2025-07-22 06:54:42 GMT+7

function sum_rec(n: number, acc: number): number {
  if ((n == 0)) {
    return acc;
  }
  return sum_rec((n - 1), (acc + n));
}
console.log((tmp => typeof tmp === 'number' && Number.isInteger(tmp) ? tmp.toFixed(1) : tmp)(sum_rec(10, 0)));
