;; Generated by Mochi 0.10.60 on 2025-08-08 11:18 +0700
#lang racket/base
(require racket/list racket/string racket/math racket/match racket/system racket/port net/url net/http-client json openssl/sha1 openssl/md5)
(define nowSeed (let ([s (getenv "MOCHI_NOW_SEED")]) (and s (string->number s))))
(define (now)
  (if nowSeed
      (begin (set! nowSeed (modulo (+ (* nowSeed 1664525) 1013904223) 2147483647)) nowSeed)
      (inexact->exact (floor (* (current-inexact-milliseconds) 1000)))))
(define (int x)
  (cond
    [(number? x) (inexact->exact (truncate x))]
    [(string? x) (let ([n (string->number x)]) (if n (inexact->exact (truncate n)) 0))]
    [else 0]))
(define (float x)
  (cond
    [(number? x) (exact->inexact x)]
    [(string? x) (let ([n (string->number x)]) (if n (exact->inexact n) 0.0))]
    [else 0.0]))
(define (input) (let ([ln (read-line)]) (if (eof-object? ln) "" ln)))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (sublist lst start end)
  (if (string? lst)
      (substring lst start end)
      (take (drop lst start) (- end start))))

(define (slice seq start end)
  (define len (if (string? seq) (string-length seq) (length seq)))
  (define s (int start))
  (define e (int end))
  (when (< s 0) (set! s (+ len s)))
  (when (< e 0) (set! e (+ len e)))
  (set! s (max 0 (min len s)))
  (set! e (max 0 (min len e)))
  (when (< e s) (set! e s))
  (if (string? seq) (substring seq s e) (sublist seq s e)))
(define (pad-start s width ch)
  (let ([s (format "~a" s)])
    (if (< (string-length s) width)
        (string-append (make-string (- width (string-length s)) (string-ref ch 0)) s)
        s)))
(define (index-of s ch)
  (cond
    [(string? s)
     (let loop ([i 0])
       (cond [(>= i (string-length s)) -1]
             [(string=? (substring s i (add1 i)) ch) i]
             [else (loop (add1 i))]))]
    [else
     (let loop ([i 0] [lst s])
       (cond [(null? lst) -1]
             [(equal? (car lst) ch) i]
             [else (loop (add1 i) (cdr lst))]))]))
(define (_repeat s n)
  (cond
    [(string? s) (apply string-append (make-list (int n) s))]
    [(list? s) (apply append (make-list (int n) s))]
    [else '()]))
(define (_parse-int-str s base) (int (string->number s base)))
(define (_sha256 bs) (bytes->list (sha256-bytes (if (string? bs) (string->bytes/utf-8 bs) (list->bytes bs)))))
(define (_fetch url) (let ([p (get-pure-port (string->url url))]) (define txt (port->string p)) (close-input-port p) (string->jsexpr txt)))
(define (num r) (numerator r))
(define (denom r) (denominator r))
(define (panic msg) (error msg))
(define Object (hash "keys" (lambda (self m) (let ([lst (hash-keys m)]) (hash "join" (lambda (s sep) (string-join lst sep)))))))
(define stdout (hash "write" (lambda (s) (display s))))

(define (sqrtApprox x)
  (let/ec _return (begin
(if (<= x 0.0) (let ()
(_return 0.0)
) (void))
(define guess x)
(define i 0)
(let/ec _break (let loop ()
  (if (< i 20) (let/ec _cont
    (set! guess (/ (let ([__l guess] [__r (/ x guess)]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))) 2.0))
    (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
(_return guess)
))
)
(define (make_knn train_data train_target class_labels)
  (let/ec _return (begin
(define items (list))
(define i 0)
(let/ec _break (let loop ()
  (if (< i (cond [(not train_data) 0] [(string? train_data) (string-length train_data)] [(hash? train_data) (hash-count train_data)] [else (length train_data)])) (let/ec _cont
    (define pl (let ([h (make-hash)]) (hash-set! h "point" (if train_data (if (hash? train_data) (hash-ref train_data i #f) (list-ref train_data (int i))) #f)) (hash-set! h "label" (if train_target (if (hash? train_target) (hash-ref train_target i #f) (list-ref train_target (int i))) #f)) h))
    (set! items (append items (list pl)))
    (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
(_return (let ([h (make-hash)]) (hash-set! h "data" items) (hash-set! h "labels" class_labels) h))
))
)
(define (euclidean_distance a b)
  (let/ec _return (begin
(define sum 0.0)
(define i 0)
(let/ec _break (let loop ()
  (if (< i (cond [(not a) 0] [(string? a) (string-length a)] [(hash? a) (hash-count a)] [else (length a)])) (let/ec _cont
    (define diff (- (if a (if (hash? a) (hash-ref a i #f) (list-ref a (int i))) #f) (if b (if (hash? b) (hash-ref b i #f) (list-ref b (int i))) #f)))
    (set! sum (let ([__l sum] [__r (* diff diff)]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
(_return (sqrtApprox sum))
))
)
(define (classify knn pred_point k)
  (let/ec _return (begin
(define distances (list))
(define i 0)
(let/ec _break (let loop ()
  (if (< i (cond [(not (if knn (hash-ref knn "data" #f) #f)) 0] [(string? (if knn (hash-ref knn "data" #f) #f)) (string-length (if knn (hash-ref knn "data" #f) #f))] [(hash? (if knn (hash-ref knn "data" #f) #f)) (hash-count (if knn (hash-ref knn "data" #f) #f))] [else (length (if knn (hash-ref knn "data" #f) #f))])) (let/ec _cont
    (define d (euclidean_distance (if (if (if knn (hash-ref knn "data" #f) #f) (if (hash? (if knn (hash-ref knn "data" #f) #f)) (hash-ref (if knn (hash-ref knn "data" #f) #f) i #f) (list-ref (if knn (hash-ref knn "data" #f) #f) (int i))) #f) (hash-ref (if (if knn (hash-ref knn "data" #f) #f) (if (hash? (if knn (hash-ref knn "data" #f) #f)) (hash-ref (if knn (hash-ref knn "data" #f) #f) i #f) (list-ref (if knn (hash-ref knn "data" #f) #f) (int i))) #f) "point" #f) #f) pred_point))
    (set! distances (append distances (list (let ([h (make-hash)]) (hash-set! h "dist" d) (hash-set! h "label" (if (if (if knn (hash-ref knn "data" #f) #f) (if (hash? (if knn (hash-ref knn "data" #f) #f)) (hash-ref (if knn (hash-ref knn "data" #f) #f) i #f) (list-ref (if knn (hash-ref knn "data" #f) #f) (int i))) #f) (hash-ref (if (if knn (hash-ref knn "data" #f) #f) (if (hash? (if knn (hash-ref knn "data" #f) #f)) (hash-ref (if knn (hash-ref knn "data" #f) #f) i #f) (list-ref (if knn (hash-ref knn "data" #f) #f) (int i))) #f) "label" #f) #f)) h))))
    (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
(define votes (list))
(define count 0)
(let/ec _break (let loop ()
  (if (< count k) (let/ec _cont
    (define min_index 0)
    (define j 1)
    (let/ec _break (let loop ()
  (if (< j (cond [(not distances) 0] [(string? distances) (string-length distances)] [(hash? distances) (hash-count distances)] [else (length distances)])) (let/ec _cont
    (if (< (if (if distances (if (hash? distances) (hash-ref distances j #f) (list-ref distances (int j))) #f) (hash-ref (if distances (if (hash? distances) (hash-ref distances j #f) (list-ref distances (int j))) #f) "dist" #f) #f) (if (if distances (if (hash? distances) (hash-ref distances min_index #f) (list-ref distances (int min_index))) #f) (hash-ref (if distances (if (hash? distances) (hash-ref distances min_index #f) (list-ref distances (int min_index))) #f) "dist" #f) #f)) (let ()
(set! min_index j)
) (void))
    (set! j (let ([__l j] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
    (set! votes (append votes (list (if (if distances (if (hash? distances) (hash-ref distances min_index #f) (list-ref distances (int min_index))) #f) (hash-ref (if distances (if (hash? distances) (hash-ref distances min_index #f) (list-ref distances (int min_index))) #f) "label" #f) #f))))
    (set! distances (list-set distances min_index (hash-set (list-ref distances min_index) "dist" 1000000000000000000.0)))
    (set! count (let ([__l count] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
(define tally (list))
(define t 0)
(let/ec _break (let loop ()
  (if (< t (cond [(not (if knn (hash-ref knn "labels" #f) #f)) 0] [(string? (if knn (hash-ref knn "labels" #f) #f)) (string-length (if knn (hash-ref knn "labels" #f) #f))] [(hash? (if knn (hash-ref knn "labels" #f) #f)) (hash-count (if knn (hash-ref knn "labels" #f) #f))] [else (length (if knn (hash-ref knn "labels" #f) #f))])) (let/ec _cont
    (set! tally (append tally (list 0)))
    (set! t (let ([__l t] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
(define v 0)
(let/ec _break (let loop ()
  (if (< v (cond [(not votes) 0] [(string? votes) (string-length votes)] [(hash? votes) (hash-count votes)] [else (length votes)])) (let/ec _cont
    (define lbl (if votes (if (hash? votes) (hash-ref votes v #f) (list-ref votes (int v))) #f))
    (set! tally (list-set tally (int lbl) (let ([__l (if tally (if (hash? tally) (hash-ref tally lbl #f) (list-ref tally (int lbl))) #f)] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r)))))
    (set! v (let ([__l v] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
(define max_idx 0)
(define m 1)
(let/ec _break (let loop ()
  (if (< m (cond [(not tally) 0] [(string? tally) (string-length tally)] [(hash? tally) (hash-count tally)] [else (length tally)])) (let/ec _cont
    (if (> (if tally (if (hash? tally) (hash-ref tally m #f) (list-ref tally (int m))) #f) (if tally (if (hash? tally) (hash-ref tally max_idx #f) (list-ref tally (int max_idx))) #f)) (let ()
(set! max_idx m)
) (void))
    (set! m (let ([__l m] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    (loop)) (void))))
(_return (if (if knn (hash-ref knn "labels" #f) #f) (if (hash? (if knn (hash-ref knn "labels" #f) #f)) (hash-ref (if knn (hash-ref knn "labels" #f) #f) max_idx #f) (list-ref (if knn (hash-ref knn "labels" #f) #f) (int max_idx))) #f))
))
)
(define train_X (list (list 0.0 0.0) (list 1.0 0.0) (list 0.0 1.0) (list 0.5 0.5) (list 3.0 3.0) (list 2.0 3.0) (list 3.0 2.0)))
(define train_y (list 0 0 0 0 1 1 1))
(define classes (list "A" "B"))
(define knn (make_knn train_X train_y classes))
(define point (list 1.2 1.2))
(let* ([_start_mem (current-memory-use)] [_start (now)])
  (let/ec _return (begin
(displayln (classify knn point 5))
    (void)
  ))
  (let* ([_end (now)] [_end_mem (current-memory-use)]
         [_dur (- _end _start)]
         [_dur_us _dur]
         [_mem (max 0 (- _end_mem _start_mem))])
    (displayln "{")
    (displayln (format "  \"duration_us\": ~a," _dur_us))
    (displayln (format "  \"memory_bytes\": ~a," _mem))
    (displayln "  \"name\": \"main\"")
    (displayln "}")
  )
)
