(* Generated by Mochi transpiler v0.10.32 on 2025-07-21 15:41 +0700 *)

exception Break
exception Continue

let () =
  let numbers = [1; 2; 3; 4; 5; 6; 7; 8; 9] in
  (try List.iter (fun n ->
    try
  if ((n mod 2) == 0) then (
  raise Continue;
  );
  if (n > 7) then (
  raise Break;
  );
  print_endline (String.concat " " ["odd number:"; string_of_int n]);
    with Continue -> ()) numbers with Break -> ())
