#!/usr/bin/env escript
% Generated by Mochi compiler v0.10.24 on 2020-01-02T15:04:05Z
% bool_chain.erl - generated from bool_chain.mochi

boom() ->
    io:format("~p~n", ["boom"]),
    true.

main(_) ->
    io:format("~p~n", [((((1 < 2)) andalso ((2 < 3))) andalso ((3 < 4)))]),
    io:format("~p~n", [((((1 < 2)) andalso ((2 > 3))) andalso boom())]),
    io:format("~p~n", [(((((1 < 2)) andalso ((2 < 3))) andalso ((3 > 4))) andalso boom())]).
