#!/usr/bin/env escript
% Generated by Mochi compiler v0.10.24 on 2020-01-02T15:04:05Z
% fun_three_args.erl - generated from fun_three_args.mochi

sum3(A, B, C) ->
    ((A + B) + C).

main(_) ->
    io:format("~p~n", [sum3(1, 2, 3)]).
