#!/usr/bin/env escript
% Generated by Mochi compiler v0.10.24 on 2020-01-02T15:04:05Z
% map_int_key.erl - generated from map_int_key.mochi

main(_) ->
    M = #{1 => "a", 2 => "b"},
    io:format("~p~n", [maps:get(1, M)]).
