// Generated by Mochi compiler v0.10.25 on 2025-07-14T06:17:42Z
// Source: /workspace/mochi/tests/vm/valid/string_compare.mochi

function main(): void {
  console.log("a" < "b");
  console.log("a" <= "a");
  console.log("b" > "a");
  console.log("b" >= "b");
}
main();
