// Generated by Mochi transpiler
bool validComb(a, b, c, d, e, f, g) {
  final int square1 = a + b;
  final int square2 = b + c + d;
  final int square3 = d + e + f;
  final int square4 = f + g;
  return square1 == square2 && square2 == square3 && square3 == square4;
}

bool isUnique(a, b, c, d, e, f, g) {
  List<int> nums = [a, b, c, d, e, f, g];
  int i = 0;
  while (i < nums.length) {
    int j = i + 1;
    while (j < nums.length) {
    if (nums[i] == nums[j]) {
    return false;
  }
    j = j + 1;
  }
    i = i + 1;
  }
  return true;
}

Map<String, dynamic> getCombs(low, high, unique) {
  List<dynamic> valid = [];
  int count = 0;
  for (int b = low; b < high + 1; b++) {
    for (int c = low; c < high + 1; c++) {
    for (int d = low; d < high + 1; d++) {
    final int s = b + c + d;
    for (int e = low; e < high + 1; e++) {
    for (int f = low; f < high + 1; f++) {
    final int a = s - b;
    final int g = s - f;
    if (a < low || a > high) {
    continue;
  }
    if (g < low || g > high) {
    continue;
  }
    if (d + e + f != s) {
    continue;
  }
    if (f + g != s) {
    continue;
  }
    if (!unique || isUnique(a, b, c, d, e, f, g)) {
    valid = [...valid, [a, b, c, d, e, f, g]];
    count = count + 1;
  }
  }
  }
  }
  }
  }
  return {"count": count, "list": valid};
}

final Map<String, dynamic> r1 = getCombs(1, 7, true);
final Map<String, dynamic> r2 = getCombs(3, 9, true);
final Map<String, dynamic> r3 = getCombs(0, 9, false);
void main() {
  print((r1["count"]!).toString() + " unique solutions in 1 to 7");
  print(r1["list"]!);
  print((r2["count"]!).toString() + " unique solutions in 3 to 9");
  print(r2["list"]!);
  print((r3["count"]!).toString() + " non-unique solutions in 0 to 9");
}
