// Generated by Mochi transpiler
String poly(int p) {
  String s = "";
  int coef = 1;
  int i = p;
  if (coef != 1) {
    s = s + (coef).toString();
  }
  while (i > 0) {
    s = s + "x";
    if (i != 1) {
    s = s + "^" + (i).toString();
  }
    coef = coef * i ~/ (p - i + 1) as int;
    int d = coef;
    if ((p - i - 1) % 2 == 1) {
    d = -d;
  }
    if (d < 0) {
    s = s + " - " + (-d).toString();
  } else {
    s = s + " + " + (d).toString();
  }
    i = i - 1;
  }
  if (s == "") {
    s = "1";
  }
  return s;
}

bool aks(int n) {
  if (n < 2) {
    return false;
  }
  int c = n;
  int i = 1;
  while (i < n) {
    if (c % n != 0) {
    return false;
  }
    c = c * (n - i) ~/ (i + 1) as int;
    i = i + 1;
  }
  return true;
}

void main() {
  int p = 0;
  while (p <= 7) {
    print((p).toString() + ":  " + poly(p));
    p = p + 1;
  }
  bool first = true;
  p = 2;
  String line = "";
  while (p < 50) {
    if (aks(p)) {
    if (first) {
    line = line + (p).toString();
    first = false;
  } else {
    line = line + " " + (p).toString();
  };
  }
    p = p + 1;
  }
  print(line);
}

void _start() {
  main();
}
