# Generated by Mochi Python compiler
from __future__ import annotations
import typing

customers: list[dict[str, typing.Any]] = [
    {id: 1, name: "Alice"},
    {id: 2, name: "Bob"},
    {id: 3, name: "Charlie"},
]
orders: list[dict[str, int]] = [
    {id: 100, customerId: 1, total: 250},
    {id: 101, customerId: 2, total: 125},
    {id: 102, customerId: 1, total: 300},
]
result: list[dict[str, int]] = [
    {
        "orderId": o["id"],
        "orderCustomerId": o["customerId"],
        "pairedCustomerName": c["name"],
        "orderTotal": o["total"],
    }
    for o in orders
    for c in customers
]
print("--- Cross Join: All order-customer pairs ---")
for entry in result:
    print(
        "Order",
        entry["orderId"],
        "(customerId:",
        entry["orderCustomerId"],
        ", total: $",
        entry["orderTotal"],
        ") paired with",
        entry["pairedCustomerName"],
    )
