# Generated by Mochi compiler v0.10.26 on 2025-07-16T17:09:25Z
from __future__ import annotations
from typing import Any, TypeVar, Generic, Callable

T = TypeVar("T")
K = TypeVar("K")


def _fmt(v):
    if isinstance(v, list):
        return " ".join((_fmt(x) for x in v))
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v)


nums = [1, 2, 3]
print(_fmt(str(2 in nums).lower()))
print(_fmt(str(4 in nums).lower()))
