# Generated by Mochi compiler v0.10.25 on 2025-07-14T12:13:49Z
prefix = "fore"
s1 = "forest"
print(str(s1[0 : len(prefix)] == prefix).lower())
s2 = "desert"
print(str(s2[0 : len(prefix)] == prefix).lower())
