// Generated by Mochi transpiler
dynamic _substr(dynamic s, num start, num end) {
  int n = s.length;
  int s0 = start.toInt();
  int e0 = end.toInt();
  if (s0 < 0) s0 += n;
  if (e0 < 0) e0 += n;
  if (s0 < 0) s0 = 0;
  if (s0 > n) s0 = n;
  if (e0 < 0) e0 = 0;
  if (e0 > n) e0 = n;
  if (s0 > e0) s0 = e0;
  if (s is String) {
    return s.substring(s0, e0);
  }
  return s.sublist(s0, e0);
}

String _str(dynamic v) { if (v is double && v == v.roundToDouble()) { var i = v.toInt(); if (i == 0) return '0'; return i.toString(); } return v.toString(); }

int solution(int n) {
  if (n <= 1) {
    return 0;
  }
  int a = 0;
  int b = 2;
  int count = 0;
  while (4 * b + a <= n) {
    int next = 4 * b + a;
    a = b;
    b = next;
    count = count + a;
  }
  return count + b;
}

void main() {
  print("solution() = " + _str(solution(4000000)));
}
