;; Generated on 2025-07-24 19:43 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi io))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (_input)
  (let ((l (read-line)))
    (if (eof-object? l) "" l)))
(define (main)
 (call/cc (lambda (ret1)
 (let ((a (let ((x2 (_input)
)
)
 (cond ((string? x2)
 (inexact->exact (string->number x2)
)
)
 ((boolean? x2)
 (if x2 1 0)
)
 (else (inexact->exact x2)
)
)
)
)
)
 (begin (let ((b (let ((x3 (_input)
)
)
 (cond ((string? x3)
 (inexact->exact (string->number x3)
)
)
 ((boolean? x3)
 (if x3 1 0)
)
 (else (inexact->exact x3)
)
)
)
)
)
 (begin (display (to-str (+ a b)
)
)
 (newline)
)
)
)
)
)
)
)
(main)
