;; Generated on 2025-07-25 01:11 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (chibi io))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (_input)
  (let ((l (read-line)))
    (if (eof-object? l) "" l)))
(define (main)
 (call/cc (lambda (ret1)
 (let ((a (let ((v2 (_input)
)
)
 (cond ((string? v2)
 (inexact->exact (string->number v2)
)
)
 ((boolean? v2)
 (if v2 1 0)
)
 (else (inexact->exact v2)
)
)
)
)
)
 (begin (let ((b (let ((v3 (_input)
)
)
 (cond ((string? v3)
 (inexact->exact (string->number v3)
)
)
 ((boolean? v3)
 (if v3 1 0)
)
 (else (inexact->exact v3)
)
)
)
)
)
 (begin (display (to-str (+ a b)
)
)
 (newline)
)
)
)
)
)
)
)
(main)
