;; Generated on 2025-07-25 01:11 +0700
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define myVar 3.14)
(display (to-str "value as float:")
)
(display " ")
(display (to-str myVar)
)
(newline)
(display (to-str "address: <not available>")
)
(newline)
