;; Generated on 2025-07-26 21:32 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start5 (now)
)
)
 (begin (define msg "Hello World! ")
 (define shift 0)
 (define inc 1)
 (define clicks 0)
 (define frames 0)
 (call/cc (lambda (break2)
 (letrec ((loop1 (lambda ()
 (if (< clicks 5)
 (begin (let ((line "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (< i (cond ((string? msg)
 (string-length msg)
)
 ((hash-table? msg)
 (hash-table-size msg)
)
 (else (length msg)
)
)
)
 (begin (let ((idx (modulo (+ shift i)
 (cond ((string? msg)
 (string-length msg)
)
 ((hash-table? msg)
 (hash-table-size msg)
)
 (else (length msg)
)
)
)
)
)
 (begin (set! line (string-append line (substring msg idx (+ idx 1)
)
)
)
 (set! i (+ i 1)
)
)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (display (to-str line)
)
 (newline)
 (set! shift (modulo (+ shift inc)
 (cond ((string? msg)
 (string-length msg)
)
 ((hash-table? msg)
 (hash-table-size msg)
)
 (else (length msg)
)
)
)
)
 (set! frames (+ frames 1)
)
 (if (equal? (modulo frames (cond ((string? msg)
 (string-length msg)
)
 ((hash-table? msg)
 (hash-table-size msg)
)
 (else (length msg)
)
)
)
 0)
 (begin (set! inc (- (cond ((string? msg)
 (string-length msg)
)
 ((hash-table? msg)
 (hash-table-size msg)
)
 (else (length msg)
)
)
 inc)
)
 (set! clicks (+ clicks 1)
)
)
 (quote ()
)
)
)
)
)
)
 (loop1)
)
 (quote ()
)
)
)
)
)
 (loop1)
)
)
)
 (let ((end6 (now)
)
)
 (let ((dur7 (quotient (- end6 start5)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur7)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
