;; Generated on 2025-07-25 01:31 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (writeTwo)
 (call/cc (lambda (ret1)
 (ret1 (list "jsmith:x:1001:1000:Joe Smith,Room 1007,(234)
555-8917,(234)
555-0077,jsmith@rosettacode.org:/home/jsmith:/bin/bash" "jdoe:x:1002:1000:Jane Doe,Room 1004,(234)
555-8914,(234)
555-0044,jdoe@rosettacode.org:/home/jsmith:/bin/bash")
)
)
)
)
(define (appendOneMore lines)
 (call/cc (lambda (ret2)
 (ret2 (append lines (list "xyz:x:1003:1000:X Yz,Room 1003,(234)
555-8913,(234)
555-0033,xyz@rosettacode.org:/home/xyz:/bin/bash")
)
)
)
)
)
(define (main)
 (call/cc (lambda (ret3)
 (let ((lines (writeTwo)
)
)
 (begin (set! lines (appendOneMore lines)
)
 (if (and (>= (cond ((string? lines)
 (string-length lines)
)
 ((hash-table? lines)
 (hash-table-size lines)
)
 (else (length lines)
)
)
 3)
 (string=? (list-ref lines 2)
 "xyz:x:1003:1000:X Yz,Room 1003,(234)
555-8913,(234)
555-0033,xyz@rosettacode.org:/home/xyz:/bin/bash")
)
 (begin (display (to-str "append okay")
)
 (newline)
)
 (begin (display (to-str "it didn't work")
)
 (newline)
)
)
)
)
)
)
)
(main)
