;; Generated on 2025-07-25 01:31 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(call/cc (lambda (break2)
 (letrec ((loop1 (lambda (xs)
 (if (null? xs)
 (quote nil)
 (begin (let ((i (car xs)
)
)
 (begin (display (to-str (to-str (* i i)
)
)
)
 (newline)
)
)
 (loop1 (cdr xs)
)
)
)
)
)
)
 (loop1 (list 1 2 3 4 5)
)
)
)
)
