;; Generated on 2025-07-25 12:33 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (main)
 (call/cc (lambda (ret1)
 (begin (display (to-str "Diagram after trimming whitespace and removal of blank lines:\n")
)
 (newline)
 (display (to-str "+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+")
)
 (newline)
 (display (to-str "|                      ID                       |")
)
 (newline)
 (display (to-str "+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+")
)
 (newline)
 (display (to-str "|QR|   Opcode  |AA|TC|RD|RA|   Z    |   RCODE   |")
)
 (newline)
 (display (to-str "+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+")
)
 (newline)
 (display (to-str "|                    QDCOUNT                    |")
)
 (newline)
 (display (to-str "+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+")
)
 (newline)
 (display (to-str "|                    ANCOUNT                    |")
)
 (newline)
 (display (to-str "+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+")
)
 (newline)
 (display (to-str "|                    NSCOUNT                    |")
)
 (newline)
 (display (to-str "+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+")
)
 (newline)
 (display (to-str "|                    ARCOUNT                    |")
)
 (newline)
 (display (to-str "+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+")
)
 (newline)
 (display (to-str "\nDecoded:\n")
)
 (newline)
 (display (to-str "Name     Bits  Start  End")
)
 (newline)
 (display (to-str "=======  ====  =====  ===")
)
 (newline)
 (display (to-str "ID        16      0    15")
)
 (newline)
 (display (to-str "QR         1     16    16")
)
 (newline)
 (display (to-str "Opcode     4     17    20")
)
 (newline)
 (display (to-str "AA         1     21    21")
)
 (newline)
 (display (to-str "TC         1     22    22")
)
 (newline)
 (display (to-str "RD         1     23    23")
)
 (newline)
 (display (to-str "RA         1     24    24")
)
 (newline)
 (display (to-str "Z          3     25    27")
)
 (newline)
 (display (to-str "RCODE      4     28    31")
)
 (newline)
 (display (to-str "QDCOUNT   16     32    47")
)
 (newline)
 (display (to-str "ANCOUNT   16     48    63")
)
 (newline)
 (display (to-str "NSCOUNT   16     64    79")
)
 (newline)
 (display (to-str "ARCOUNT   16     80    95")
)
 (newline)
 (display (to-str "\nTest string in hex:")
)
 (newline)
 (display (to-str "78477bbf5496e12e1bf169a4")
)
 (newline)
 (display (to-str "\nTest string in binary:")
)
 (newline)
 (display (to-str "011110000100011101111011101111110101010010010110111000010010111000011011111100010110100110100100")
)
 (newline)
 (display (to-str "\nUnpacked:\n")
)
 (newline)
 (display (to-str "Name     Size  Bit pattern")
)
 (newline)
 (display (to-str "=======  ====  ================")
)
 (newline)
 (display (to-str "ID        16   0111100001000111")
)
 (newline)
 (display (to-str "QR         1   0")
)
 (newline)
 (display (to-str "Opcode     4   1111")
)
 (newline)
 (display (to-str "AA         1   0")
)
 (newline)
 (display (to-str "TC         1   1")
)
 (newline)
 (display (to-str "RD         1   1")
)
 (newline)
 (display (to-str "RA         1   1")
)
 (newline)
 (display (to-str "Z          3   011")
)
 (newline)
 (display (to-str "RCODE      4   1111")
)
 (newline)
 (display (to-str "QDCOUNT   16   0101010010010110")
)
 (newline)
 (display (to-str "ANCOUNT   16   1110000100101110")
)
 (newline)
 (display (to-str "NSCOUNT   16   0001101111110001")
)
 (newline)
 (display (to-str "ARCOUNT   16   0110100110100100")
)
 (newline)
)
)
)
)
(main)
