;; Generated on 2025-07-28 11:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (createFile fs fn)
 (call/cc (lambda (ret1)
 (if (cond ((string? fs)
 (if (string-contains fs fn)
 #t #f)
)
 ((hash-table? fs)
 (if (hash-table-exists? fs fn)
 #t #f)
)
 (else (if (member fn fs)
 #t #f)
)
)
 (begin (_display (to-str (string-append (string-append "open " fn)
 ": file exists")
)
)
 (newline)
)
 (begin (hash-table-set! fs fn #f)
 (_display (to-str (string-append (string-append "file " fn)
 " created!")
)
)
 (newline)
)
)
)
)
)
(define (createDir fs dn)
 (call/cc (lambda (ret2)
 (if (cond ((string? fs)
 (if (string-contains fs dn)
 #t #f)
)
 ((hash-table? fs)
 (if (hash-table-exists? fs dn)
 #t #f)
)
 (else (if (member dn fs)
 #t #f)
)
)
 (begin (_display (to-str (string-append (string-append "mkdir " dn)
 ": file exists")
)
)
 (newline)
)
 (begin (hash-table-set! fs dn #t)
 (_display (to-str (string-append (string-append "directory " dn)
 " created!")
)
)
 (newline)
)
)
)
)
)
(define (main)
 (call/cc (lambda (ret3)
 (let ((fs (alist->hash-table (_list)
)
)
)
 (begin (hash-table-set! fs "docs" #t)
 (createFile fs "input.txt")
 (createFile fs "/input.txt")
 (createDir fs "docs")
 (createDir fs "/docs")
)
)
)
)
)
(main)
