;; Generated on 2025-07-28 11:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (gzipWriter w)
 (call/cc (lambda (ret1)
 (ret1 w)
)
)
)
(define (tarWriter w)
 (call/cc (lambda (ret2)
 (ret2 w)
)
)
)
(define (tarWriteHeader w hdr)
 (call/cc (lambda (ret3)
 (begin)
)
)
)
(define (tarWrite w data)
 (call/cc (lambda (ret4)
 (begin)
)
)
)
(define (main)
 (call/cc (lambda (ret5)
 (let ((filename "TAPE.FILE")
)
 (begin (let ((data "")
)
 (begin (let ((outfile "")
)
 (begin (let ((gzipFlag #f)
)
 (begin (let ((w (quote ()
)
)
)
 (begin (if (not (string=? outfile "")
)
 (begin (set! w (quote ()
)
)
)
 (quote ()
)
)
 (if gzipFlag (begin (set! w (gzipWriter w)
)
)
 (quote ()
)
)
 (set! w (tarWriter w)
)
 (let ((hdr (alist->hash-table (_list (cons "Name" filename)
 (cons "Mode" 432)
 (cons "Size" (cond ((string? data)
 (string-length data)
)
 ((hash-table? data)
 (hash-table-size data)
)
 (else (length data)
)
)
)
 (cons "ModTime" (now)
)
 (cons "Typeflag" 0)
 (cons "Uname" "guest")
 (cons "Gname" "guest")
)
)
)
)
 (begin (tarWriteHeader w hdr)
 (tarWrite w data)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
(main)
