;; Generated on 2025-07-28 11:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (main)
 (call/cc (lambda (ret1)
 (let ((row 3)
)
 (begin (let ((col 4)
)
 (begin (let ((a (_list)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i row)
 (begin (let ((rowArr (_list)
)
)
 (begin (let ((j 0)
)
 (begin (call/cc (lambda (break5)
 (letrec ((loop4 (lambda ()
 (if (< j col)
 (begin (set! rowArr (append rowArr (_list 0)
)
)
 (set! j (+ j 1)
)
 (loop4)
)
 (quote ()
)
)
)
)
)
 (loop4)
)
)
)
 (set! a (append a (_list rowArr)
)
)
 (set! i (+ i 1)
)
)
)
)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (_display (to-str (string-append "a[0][0] = " (to-str (cond ((string? (list-ref a 0)
)
 (substring (list-ref a 0)
 0 (+ 0 1)
)
)
 ((hash-table? (list-ref a 0)
)
 (hash-table-ref (list-ref a 0)
 0)
)
 (else (list-ref (list-ref a 0)
 0)
)
)
)
)
)
)
 (newline)
 (list-set! (list-ref a (let ((v6 (- row 1)
)
)
 (cond ((string? v6)
 (inexact->exact (floor (string->number v6)
)
)
)
 ((boolean? v6)
 (if v6 1 0)
)
 (else (inexact->exact (floor v6)
)
)
)
)
)
 (let ((v7 (- col 1)
)
)
 (cond ((string? v7)
 (inexact->exact (floor (string->number v7)
)
)
)
 ((boolean? v7)
 (if v7 1 0)
)
 (else (inexact->exact (floor v7)
)
)
)
)
 7)
 (_display (to-str (string-append (string-append (string-append (string-append (string-append "a[" (to-str (- row 1)
)
)
 "][")
 (to-str (- col 1)
)
)
 "] = ")
 (to-str (cond ((string? (list-ref a (let ((v8 (- row 1)
)
)
 (cond ((string? v8)
 (inexact->exact (floor (string->number v8)
)
)
)
 ((boolean? v8)
 (if v8 1 0)
)
 (else (inexact->exact (floor v8)
)
)
)
)
)
)
 (substring (list-ref a (let ((v8 (- row 1)
)
)
 (cond ((string? v8)
 (inexact->exact (floor (string->number v8)
)
)
)
 ((boolean? v8)
 (if v8 1 0)
)
 (else (inexact->exact (floor v8)
)
)
)
)
)
 (let ((v9 (- col 1)
)
)
 (cond ((string? v9)
 (inexact->exact (floor (string->number v9)
)
)
)
 ((boolean? v9)
 (if v9 1 0)
)
 (else (inexact->exact (floor v9)
)
)
)
)
 (+ (let ((v9 (- col 1)
)
)
 (cond ((string? v9)
 (inexact->exact (floor (string->number v9)
)
)
)
 ((boolean? v9)
 (if v9 1 0)
)
 (else (inexact->exact (floor v9)
)
)
)
)
 1)
)
)
 ((hash-table? (list-ref a (let ((v8 (- row 1)
)
)
 (cond ((string? v8)
 (inexact->exact (floor (string->number v8)
)
)
)
 ((boolean? v8)
 (if v8 1 0)
)
 (else (inexact->exact (floor v8)
)
)
)
)
)
)
 (hash-table-ref (list-ref a (let ((v8 (- row 1)
)
)
 (cond ((string? v8)
 (inexact->exact (floor (string->number v8)
)
)
)
 ((boolean? v8)
 (if v8 1 0)
)
 (else (inexact->exact (floor v8)
)
)
)
)
)
 (let ((v9 (- col 1)
)
)
 (cond ((string? v9)
 (inexact->exact (floor (string->number v9)
)
)
)
 ((boolean? v9)
 (if v9 1 0)
)
 (else (inexact->exact (floor v9)
)
)
)
)
)
)
 (else (list-ref (list-ref a (let ((v8 (- row 1)
)
)
 (cond ((string? v8)
 (inexact->exact (floor (string->number v8)
)
)
)
 ((boolean? v8)
 (if v8 1 0)
)
 (else (inexact->exact (floor v8)
)
)
)
)
)
 (let ((v9 (- col 1)
)
)
 (cond ((string? v9)
 (inexact->exact (floor (string->number v9)
)
)
)
 ((boolean? v9)
 (if v9 1 0)
)
 (else (inexact->exact (floor v9)
)
)
)
)
)
)
)
)
)
)
)
 (newline)
 (set! a (quote ()
)
)
)
)
)
)
)
)
)
)
)
)
)
(main)
