;; Generated on 2025-07-28 11:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (main)
 (call/cc (lambda (ret1)
 (let ((rows (_list)
)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda (i)
 (if (< i 4)
 (begin (begin (set! rows (append rows (_list (_list (* i 3)
 (_add (* i 3)
 1)
 (_add (* i 3)
 2)
)
)
)
)
)
 (loop2 (+ i 1)
)
)
 (quote ()
)
)
)
)
)
 (loop2 0)
)
)
)
 (_display (to-str "<table>")
)
 (newline)
 (_display (to-str "    <tr><th></th><th>X</th><th>Y</th><th>Z</th></tr>")
)
 (newline)
 (let ((idx 0)
)
 (begin (call/cc (lambda (break5)
 (letrec ((loop4 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((row (car xs)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append "    <tr><td>" (to-str idx)
)
 "</td><td>")
 (to-str (cond ((string? row)
 (substring row 0 (+ 0 1)
)
)
 ((hash-table? row)
 (hash-table-ref row 0)
)
 (else (list-ref row 0)
)
)
)
)
 "</td><td>")
 (to-str (cond ((string? row)
 (substring row 1 (+ 1 1)
)
)
 ((hash-table? row)
 (hash-table-ref row 1)
)
 (else (list-ref row 1)
)
)
)
)
 "</td><td>")
 (to-str (cond ((string? row)
 (substring row 2 (+ 2 1)
)
)
 ((hash-table? row)
 (hash-table-ref row 2)
)
 (else (list-ref row 2)
)
)
)
)
 "</td></tr>")
)
)
 (newline)
 (set! idx (+ idx 1)
)
)
)
 (loop4 (cdr xs)
)
)
)
)
)
)
 (loop4 rows)
)
)
)
 (_display (to-str "</table>")
)
 (newline)
)
)
)
)
)
)
)
(main)
