;; Generated on 2025-07-28 11:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(define (pow base exp)
 (call/cc (lambda (ret1)
 (let ((result 1.0)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (< i (let ((v2 exp)
)
 (cond ((string? v2)
 (exact (floor (string->number v2)
)
)
)
 ((boolean? v2)
 (if v2 1 0)
)
 (else (exact (floor v2)
)
)
)
)
)
 (begin (set! result (* result base)
)
 (set! i (+ i 1)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (ret1 result)
)
)
)
)
)
)
)
(define (PowN b)
 (call/cc (lambda (ret5)
 (ret5 (lambda (e)
 (expt b e)
)
)
)
)
)
(define (PowE e)
 (call/cc (lambda (ret6)
 (ret6 (lambda (b)
 (expt b e)
)
)
)
)
)
(define (Method self b)
 (call/cc (lambda (ret7)
 (ret7 (_add "value" b)
)
)
)
)
(define (main)
 (call/cc (lambda (ret8)
 (let ((pow2 (PowN 2.0)
)
)
 (begin (let ((cube (PowE 3.0)
)
)
 (begin (_display (to-str (string-append "2^8 = " (to-str (pow2 8.0)
)
)
)
)
 (newline)
 (_display (to-str (string-append "4³ = " (to-str (cube 4.0)
)
)
)
)
 (newline)
 (let ((a (alist->hash-table (_list (cons "value" 2)
)
)
)
)
 (begin (let ((fn1 (lambda (b)
 (Method a b)
)
)
)
 (begin (let ((fn2 (lambda (f b)
 (Method f b)
)
)
)
 (begin (_display (to-str (string-append "2 + 2 = " (to-str (Method a 2)
)
)
)
)
 (newline)
 (_display (to-str (string-append "2 + 3 = " (to-str (fn1 3)
)
)
)
)
 (newline)
 (_display (to-str (string-append "2 + 4 = " (to-str (fn2 a 4)
)
)
)
)
 (newline)
 (_display (to-str (string-append "3 + 5 = " (to-str (fn2 (alist->hash-table (_list (cons "value" 3)
)
)
 5)
)
)
)
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
)
)
(main)
