;; Generated on 2025-07-28 11:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(define (padLeft n width)
 (call/cc (lambda (ret1)
 (let ((s (to-str n)
)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 width)
 (begin (set! s (string-append " " s)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 s)
)
)
)
)
)
(define (squeeze s ch)
 (call/cc (lambda (ret4)
 (let ((out "")
)
 (begin (let ((prev #f)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< i (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 (begin (let ((c (substring s i (+ i 1)
)
)
)
 (begin (if (string=? c ch)
 (begin (if (not prev)
 (begin (set! out (string-append out c)
)
 (set! prev #t)
)
 (quote ()
)
)
)
 (begin (set! out (string-append out c)
)
 (set! prev #f)
)
)
 (set! i (+ i 1)
)
)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (ret4 out)
)
)
)
)
)
)
)
)
)
(define strings (_list "" "\"If I were two-faced, would I be wearing this one?\" --- Abraham Lincoln " "..1111111111111111111111111111111111111111111111111111111111111117777888" "I never give 'em hell, I just tell the truth, and they think it's hell. " "                                                   ---  Harry S Truman  " "The better the 4-wheel drive, the further you'll be from help when ya get stuck!" "headmistressship" "aardvark" "😍😀🙌💃😍😍😍🙌")
)
(define chars (_list (_list " ")
 (_list "-")
 (_list "7")
 (_list ".")
 (_list " " "-" "r")
 (_list "e")
 (_list "s")
 (_list "a")
 (_list "😍")
)
)
(define i 0)
(call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if (< i (cond ((string? strings)
 (string-length strings)
)
 ((hash-table? strings)
 (hash-table-size strings)
)
 (else (length strings)
)
)
)
 (begin (let ((j 0)
)
 (begin (let ((s (list-ref strings i)
)
)
 (begin (call/cc (lambda (break10)
 (letrec ((loop9 (lambda ()
 (if (< j (cond ((string? (list-ref chars i)
)
 (string-length (list-ref chars i)
)
)
 ((hash-table? (list-ref chars i)
)
 (hash-table-size (list-ref chars i)
)
)
 (else (length (list-ref chars i)
)
)
)
)
 (begin (let ((c (cond ((string? (list-ref chars i)
)
 (substring (list-ref chars i)
 j (+ j 1)
)
)
 ((hash-table? (list-ref chars i)
)
 (hash-table-ref (list-ref chars i)
 j)
)
 (else (list-ref (list-ref chars i)
 j)
)
)
)
)
 (begin (let ((ss (squeeze s c)
)
)
 (begin (_display (to-str (string-append (string-append "specified character = '" c)
 "'")
)
)
 (newline)
 (_display (to-str (string-append (string-append (string-append (string-append "original : length = " (padLeft (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 2)
)
 ", string = «««")
 s)
 "»»»")
)
)
 (newline)
 (_display (to-str (string-append (string-append (string-append (string-append "squeezed : length = " (padLeft (cond ((string? ss)
 (string-length ss)
)
 ((hash-table? ss)
 (hash-table-size ss)
)
 (else (length ss)
)
)
 2)
)
 ", string = «««")
 ss)
 "»»»")
)
)
 (newline)
 (_display (to-str "")
)
 (newline)
 (set! j (+ j 1)
)
)
)
)
)
 (loop9)
)
 (quote ()
)
)
)
)
)
 (loop9)
)
)
)
 (set! i (+ i 1)
)
)
)
)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
