;; Generated on 2025-07-25 08:58 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (* (current-seconds) 1000000000)))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi net) (scheme sort) (chibi string))
(define (_lookup_host host)
  (with-exception-handler
   (lambda (e) (list '() e))
   (lambda ()
     (let loop ((a (get-address-info host "http")) (acc '()))
       (if a
           (let ((addr (sockaddr-name (address-info-address a))))
             (loop (address-info-next a)
                   (if (string-contains addr ":") acc (cons addr acc))))
          (list (list-sort string<? acc) 'nil))))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(let ((start1 (now)
)
)
 (begin (define res (_lookup_host "www.kame.net")
)
 (define addrs (list-ref res 0)
)
 (define err (list-ref res 1)
)
 (if (equal? err (quote nil)
)
 (begin (display (to-str (to-str addrs)
)
)
 (newline)
)
 (begin (display (to-str err)
)
 (newline)
)
)
 (let ((end2 (now)
)
)
 (let ((dur3 (quotient (- end2 start1)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur3)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
