;; Generated on 2025-07-24 19:43 +0700
(import (chibi net) (scheme sort) (chibi string))
(define (_lookup_host host)
  (with-exception-handler
   (lambda (e) (list '() e))
   (lambda ()
     (let loop ((a (get-address-info host "http")) (acc '()))
       (if a
           (let ((addr (sockaddr-name (address-info-address a))))
             (loop (address-info-next a)
                   (if (string-contains addr ":") acc (cons addr acc))))
          (list (list-sort string<? acc) 'nil))))))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define res (_lookup_host "www.kame.net")
)
(define addrs (list-ref res 0)
)
(define err (list-ref res 1)
)
(if (equal? err (quote nil)
)
 (begin (display (to-str (to-str addrs)
)
)
 (newline)
)
 (begin (display (to-str err)
)
 (newline)
)
)
