;; Generated on 2025-07-28 10:03 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(let ((start9 (now)
)
)
 (begin (define nodes (alist->hash-table (_list)
)
)
 (define head (- 0 1)
)
 (define tail (- 0 1)
)
 (define (listString)
 (call/cc (lambda (ret1)
 (begin (if (equal? head (- 0 1)
)
 (begin (ret1 "<nil>")
)
 (quote ()
)
)
 (let ((r (string-append "[" (cond ((string? (hash-table-ref/default nodes head (quote ()
)
)
)
 (substring (hash-table-ref/default nodes head (quote ()
)
)
 "value" (+ "value" 1)
)
)
 ((hash-table? (hash-table-ref/default nodes head (quote ()
)
)
)
 (hash-table-ref (hash-table-ref/default nodes head (quote ()
)
)
 "value")
)
 (else (list-ref (hash-table-ref/default nodes head (quote ()
)
)
 "value")
)
)
)
)
)
 (begin (let ((id (let ((v2 (cond ((string? (hash-table-ref/default nodes head (quote ()
)
)
)
 (substring (hash-table-ref/default nodes head (quote ()
)
)
 "next" (+ "next" 1)
)
)
 ((hash-table? (hash-table-ref/default nodes head (quote ()
)
)
)
 (hash-table-ref (hash-table-ref/default nodes head (quote ()
)
)
 "next")
)
 (else (list-ref (hash-table-ref/default nodes head (quote ()
)
)
 "next")
)
)
)
)
 (cond ((string? v2)
 (exact (floor (string->number v2)
)
)
)
 ((boolean? v2)
 (if v2 1 0)
)
 (else (exact (floor v2)
)
)
)
)
)
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (not (equal? id (- 0 1)
)
)
 (begin (set! r (string-append (string-append r " ")
 (cond ((string? (hash-table-ref/default nodes id (quote ()
)
)
)
 (substring (hash-table-ref/default nodes id (quote ()
)
)
 "value" (+ "value" 1)
)
)
 ((hash-table? (hash-table-ref/default nodes id (quote ()
)
)
)
 (hash-table-ref (hash-table-ref/default nodes id (quote ()
)
)
 "value")
)
 (else (list-ref (hash-table-ref/default nodes id (quote ()
)
)
 "value")
)
)
)
)
 (set! id (let ((v5 (cond ((string? (hash-table-ref/default nodes id (quote ()
)
)
)
 (substring (hash-table-ref/default nodes id (quote ()
)
)
 "next" (+ "next" 1)
)
)
 ((hash-table? (hash-table-ref/default nodes id (quote ()
)
)
)
 (hash-table-ref (hash-table-ref/default nodes id (quote ()
)
)
 "next")
)
 (else (list-ref (hash-table-ref/default nodes id (quote ()
)
)
 "next")
)
)
)
)
 (cond ((string? v5)
 (exact (floor (string->number v5)
)
)
)
 ((boolean? v5)
 (if v5 1 0)
)
 (else (exact (floor v5)
)
)
)
)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (set! r (string-append r "]")
)
 (ret1 r)
)
)
)
)
)
)
)
)
 (_display (to-str (listString)
)
)
 (newline)
 (hash-table-set! nodes 0 (alist->hash-table (_list (cons "value" "A")
 (cons "next" (- 0 1)
)
 (cons "prev" (- 0 1)
)
)
)
)
 (set! head 0)
 (set! tail 0)
 (hash-table-set! nodes 1 (alist->hash-table (_list (cons "value" "B")
 (cons "next" (- 0 1)
)
 (cons "prev" 0)
)
)
)
 (hash-table-set! (hash-table-ref/default nodes 0 (quote ()
)
)
 "next" 1)
 (set! tail 1)
 (_display (to-str (listString)
)
)
 (newline)
 (hash-table-set! nodes 2 (alist->hash-table (_list (cons "value" "C")
 (cons "next" 1)
 (cons "prev" 0)
)
)
)
 (hash-table-set! (hash-table-ref/default nodes 1 (quote ()
)
)
 "prev" 2)
 (hash-table-set! (hash-table-ref/default nodes 0 (quote ()
)
)
 "next" 2)
 (_display (to-str (listString)
)
)
 (newline)
 (define out "From tail:")
 (define id tail)
 (call/cc (lambda (break7)
 (letrec ((loop6 (lambda ()
 (if (not (equal? id (- 0 1)
)
)
 (begin (set! out (string-append (string-append out " ")
 (cond ((string? (hash-table-ref/default nodes id (quote ()
)
)
)
 (substring (hash-table-ref/default nodes id (quote ()
)
)
 "value" (+ "value" 1)
)
)
 ((hash-table? (hash-table-ref/default nodes id (quote ()
)
)
)
 (hash-table-ref (hash-table-ref/default nodes id (quote ()
)
)
 "value")
)
 (else (list-ref (hash-table-ref/default nodes id (quote ()
)
)
 "value")
)
)
)
)
 (set! id (let ((v8 (cond ((string? (hash-table-ref/default nodes id (quote ()
)
)
)
 (substring (hash-table-ref/default nodes id (quote ()
)
)
 "prev" (+ "prev" 1)
)
)
 ((hash-table? (hash-table-ref/default nodes id (quote ()
)
)
)
 (hash-table-ref (hash-table-ref/default nodes id (quote ()
)
)
 "prev")
)
 (else (list-ref (hash-table-ref/default nodes id (quote ()
)
)
 "prev")
)
)
)
)
 (cond ((string? v8)
 (exact (floor (string->number v8)
)
)
)
 ((boolean? v8)
 (if v8 1 0)
)
 (else (exact (floor v8)
)
)
)
)
)
 (loop6)
)
 (quote ()
)
)
)
)
)
 (loop6)
)
)
)
 (_display (to-str out)
)
 (newline)
 (let ((end10 (now)
)
)
 (let ((dur11 (quotient (- end10 start9)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur11)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
