;; Generated on 2025-07-28 10:03 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(let ((start7 (now)
)
)
 (begin (define (Node value next prev)
 (call/cc (lambda (ret1)
 (ret1 (alist->hash-table (_list (cons "value" value)
 (cons "next" next)
 (cons "prev" prev)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret2)
 (let ((a (Node "A" (quote ()
)
 (quote ()
)
)
)
)
 (begin (let ((b (Node "B" (quote ()
)
 a)
)
)
 (begin (list-set! a "next" b)
 (let ((c (Node "C" (quote ()
)
 b)
)
)
 (begin (list-set! b "next" c)
 (let ((p a)
)
 (begin (let ((line "")
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (not (equal? p (quote ()
)
)
)
 (begin (set! line (string-append line (to-str (cond ((string? p)
 (substring p "value" (+ "value" 1)
)
)
 ((hash-table? p)
 (hash-table-ref p "value")
)
 (else (list-ref p "value")
)
)
)
)
)
 (set! p (cond ((string? p)
 (substring p "next" (+ "next" 1)
)
)
 ((hash-table? p)
 (hash-table-ref p "next")
)
 (else (list-ref p "next")
)
)
)
 (if (not (equal? p (quote ()
)
)
)
 (begin (set! line (string-append line " ")
)
)
 (quote ()
)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (_display (to-str line)
)
 (newline)
 (set! p c)
 (set! line "")
 (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (not (equal? p (quote ()
)
)
)
 (begin (set! line (string-append line (to-str (cond ((string? p)
 (substring p "value" (+ "value" 1)
)
)
 ((hash-table? p)
 (hash-table-ref p "value")
)
 (else (list-ref p "value")
)
)
)
)
)
 (set! p (cond ((string? p)
 (substring p "prev" (+ "prev" 1)
)
)
 ((hash-table? p)
 (hash-table-ref p "prev")
)
 (else (list-ref p "prev")
)
)
)
 (if (not (equal? p (quote ()
)
)
)
 (begin (set! line (string-append line " ")
)
)
 (quote ()
)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (_display (to-str line)
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end8 (now)
)
)
 (let ((dur9 (quotient (- end8 start7)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur9)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
