;; Generated on 2025-07-28 10:03 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(let ((start21 (now)
)
)
 (begin (define (bitAt x idx)
 (call/cc (lambda (ret1)
 (let ((v x)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i idx)
 (begin (set! v (let ((v4 (quotient v 2)
)
)
 (cond ((string? v4)
 (exact (floor (string->number v4)
)
)
)
 ((boolean? v4)
 (if v4 1 0)
)
 (else (exact (floor v4)
)
)
)
)
)
 (set! i (+ i 1)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 (modulo v 2)
)
)
)
)
)
)
)
)
 (define (outputState state)
 (call/cc (lambda (ret5)
 (let ((line "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break7)
 (letrec ((loop6 (lambda ()
 (if (< i (cond ((string? state)
 (string-length state)
)
 ((hash-table? state)
 (hash-table-size state)
)
 (else (length state)
)
)
)
 (begin (if (string=? (substring state i (+ i 1)
)
 "1")
 (begin (set! line (string-append line "#")
)
)
 (begin (set! line (string-append line " ")
)
)
)
 (set! i (+ i 1)
)
 (loop6)
)
 (quote ()
)
)
)
)
)
 (loop6)
)
)
)
 (_display (to-str line)
)
 (newline)
)
)
)
)
)
)
)
 (define (step state r)
 (call/cc (lambda (ret8)
 (let ((cells (cond ((string? state)
 (string-length state)
)
 ((hash-table? state)
 (hash-table-size state)
)
 (else (length state)
)
)
)
)
 (begin (let ((out "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break10)
 (letrec ((loop9 (lambda ()
 (if (< i cells)
 (begin (let ((l (substring state (modulo (_add (- i 1)
 cells)
 cells)
 (_add (modulo (_add (- i 1)
 cells)
 cells)
 1)
)
)
)
 (begin (let ((c (substring state i (+ i 1)
)
)
)
 (begin (let ((rt (substring state (modulo (+ i 1)
 cells)
 (_add (modulo (+ i 1)
 cells)
 1)
)
)
)
 (begin (let ((idx 0)
)
 (begin (if (string=? l "1")
 (begin (set! idx (+ idx 4)
)
)
 (quote ()
)
)
 (if (string=? c "1")
 (begin (set! idx (+ idx 2)
)
)
 (quote ()
)
)
 (if (string=? rt "1")
 (begin (set! idx (+ idx 1)
)
)
 (quote ()
)
)
 (if (equal? (bitAt r idx)
 1)
 (begin (set! out (string-append out "1")
)
)
 (begin (set! out (string-append out "0")
)
)
)
 (set! i (+ i 1)
)
)
)
)
)
)
)
)
)
 (loop9)
)
 (quote ()
)
)
)
)
)
 (loop9)
)
)
)
 (ret8 out)
)
)
)
)
)
)
)
)
)
 (define (elem r cells generations state)
 (call/cc (lambda (ret11)
 (begin (outputState state)
 (let ((g 0)
)
 (begin (let ((s state)
)
 (begin (call/cc (lambda (break13)
 (letrec ((loop12 (lambda ()
 (if (< g generations)
 (begin (set! s (step s r)
)
 (outputState s)
 (set! g (+ g 1)
)
 (loop12)
)
 (quote ()
)
)
)
)
)
 (loop12)
)
)
)
)
)
)
)
)
)
)
)
 (define (randInit cells seed)
 (call/cc (lambda (ret14)
 (let ((s "")
)
 (begin (let ((val seed)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break16)
 (letrec ((loop15 (lambda ()
 (if (< i cells)
 (begin (set! val (modulo (_add (* val 1664525)
 1013904223)
 2147483647)
)
 (if (equal? (modulo val 2)
 0)
 (begin (set! s (string-append s "0")
)
)
 (begin (set! s (string-append s "1")
)
)
)
 (set! i (+ i 1)
)
 (loop15)
)
 (quote ()
)
)
)
)
)
 (loop15)
)
)
)
 (ret14 s)
)
)
)
)
)
)
)
)
)
 (define (singleInit cells)
 (call/cc (lambda (ret17)
 (let ((s "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break19)
 (letrec ((loop18 (lambda ()
 (if (< i cells)
 (begin (if (equal? i (quotient cells 2)
)
 (begin (set! s (string-append s "1")
)
)
 (begin (set! s (string-append s "0")
)
)
)
 (set! i (+ i 1)
)
 (loop18)
)
 (quote ()
)
)
)
)
)
 (loop18)
)
)
)
 (ret17 s)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret20)
 (let ((cells 20)
)
 (begin (let ((generations 9)
)
 (begin (_display (to-str "Single 1, rule 90:")
)
 (newline)
 (let ((state (singleInit cells)
)
)
 (begin (elem 90 cells generations state)
 (_display (to-str "Random intial state, rule 30:")
)
 (newline)
 (set! state (randInit cells 3)
)
 (elem 30 cells generations state)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end22 (now)
)
)
 (let ((dur23 (quotient (- end22 start21)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur23)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
