;; Generated on 2025-08-01 15:22 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(define (capitalize s)
 (call/cc (lambda (ret1)
 (begin (if (equal? (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 0)
 (begin (ret1 s)
)
 (quote ()
)
)
 (ret1 (string-append (upper (substring s 0 1)
)
 (substring s 1 (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
)
)
)
)
)
)
(define small (_list "zero" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine" "ten" "eleven" "twelve" "thirteen" "fourteen" "fifteen" "sixteen" "seventeen" "eighteen" "nineteen")
)
(define tens (_list "" "" "twenty" "thirty" "forty" "fifty" "sixty" "seventy" "eighty" "ninety")
)
(define illions (_list "" " thousand" " million" " billion" " trillion" " quadrillion" " quintillion")
)
(define (say n)
 (call/cc (lambda (ret2)
 (let ((t "")
)
 (begin (if (< n 0)
 (begin (set! t "negative ")
 (set! n (- n)
)
)
 (quote ()
)
)
 (if (< n 20)
 (begin (ret2 (string-append t (list-ref small n)
)
)
)
 (if (< n 100)
 (begin (set! t (list-ref tens (quotient n 10)
)
)
 (let ((s (modulo n 10)
)
)
 (begin (if (> s 0)
 (begin (set! t (string-append (string-append t "-")
 (list-ref small s)
)
)
)
 (quote ()
)
)
 (ret2 t)
)
)
)
 (if (< n 1000)
 (begin (set! t (string-append (list-ref small (quotient n 100)
)
 " hundred")
)
 (let ((s (modulo n 100)
)
)
 (begin (if (> s 0)
 (begin (set! t (string-append (string-append t " ")
 (say s)
)
)
)
 (quote ()
)
)
 (ret2 t)
)
)
)
 (quote ()
)
)
)
)
 (let ((sx "")
)
 (begin (let ((i 0)
)
 (begin (let ((nn n)
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (> nn 0)
 (begin (let ((p (modulo nn 1000)
)
)
 (begin (set! nn (quotient nn 1000)
)
 (if (> p 0)
 (begin (let ((ix (string-append (say p)
 (list-ref illions i)
)
)
)
 (begin (if (not (string=? sx "")
)
 (begin (set! ix (string-append (string-append ix " ")
 sx)
)
)
 (quote ()
)
)
 (set! sx ix)
)
)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (ret2 (string-append t sx)
)
)
)
)
)
)
)
)
)
)
)
)
(define (fourIsMagic n)
 (call/cc (lambda (ret5)
 (let ((s (say n)
)
)
 (begin (set! s (capitalize s)
)
 (let ((t s)
)
 (begin (call/cc (lambda (break7)
 (letrec ((loop6 (lambda ()
 (if (not (equal? n 4)
)
 (begin (set! n (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 (set! s (say n)
)
 (set! t (string-append (string-append (string-append (string-append t " is ")
 s)
 ", ")
 s)
)
 (loop6)
)
 (quote ()
)
)
)
)
)
 (loop6)
)
)
)
 (set! t (string-append t " is magic.")
)
 (ret5 t)
)
)
)
)
)
)
)
(define (main)
 (call/cc (lambda (ret8)
 (let ((nums (_list 0 4 6 11 13 75 100 337 (- 164)
 9223372036854775807)
)
)
 (begin (call/cc (lambda (break10)
 (letrec ((loop9 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((n (car xs)
)
)
 (begin (_display (to-str (fourIsMagic n)
)
)
 (newline)
)
)
 (loop9 (cdr xs)
)
)
)
)
)
)
 (loop9 nums)
)
)
)
)
)
)
)
)
(main)
